<a href="https://colab.research.google.com/github/mathuraryan036-collab/DL-GOOGLE-COLAB/blob/main/12_Batch_vs_Stochastic_GD.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import pandas as pd
import time

In [ ]:
df = pd.read_csv('/content/Social_Network_Ads.csv')

In [ ]:
df.head()

    User ID  Gender  Age  EstimatedSalary  Purchased
0  15624510    Male   19            19000          0
1  15810944    Male   35            20000          0
2  15668575  Female   26            43000          0
3  15603246  Female   27            57000          0
4  15804002    Male   19            76000          0

In [ ]:
df = df[['Age', 'EstimatedSalary', 'Purchased']]

In [ ]:
df.head()

   Age  EstimatedSalary  Purchased
0   19            19000          0
1   35            20000          0
2   26            43000          0
3   27            57000          0
4   19            76000          0

In [ ]:
X = df.iloc[:, 0:2]
Y = df.iloc[:, -1]

In [ ]:
X

     Age  EstimatedSalary
0     19            19000
1     35            20000
2     26            43000
3     27            57000
4     19            76000
..   ...              ...
395   46            41000
396   51            23000
397   50            20000
398   36            33000
399   49            36000

[400 rows x 2 columns]

In [ ]:
Y

0      0
1      0
2      0
3      0
4      0
      ..
395    1
396    1
397    1
398    0
399    1
Name: Purchased, Length: 400, dtype: int64

In [ ]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()

X_scaled = scaler.fit_transform(X)

In [ ]:
# for checking which converges faster
X_scaled.shape

(400, 2)

In [ ]:
# for checking which is faster
# from sklearn.model_selection import train_test_split
# X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.2, random_state=2)

In [ ]:
# for checking which is faster
# X_train.shape

(320, 2)

In [ ]:
import tensorflow as tf
from tensorflow import keras
from keras import Sequential
from keras.layers import Dense

In [ ]:
model = Sequential()

In [ ]:
model.add(Dense(10, activation='relu', input_dim=2))
model.add(Dense(10, activation='relu'))
model.add(Dense(1,  activation='sigmoid'))

In [ ]:
model.summary()

Model: "sequential_2"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense_6 (Dense)                 │ (None, 10)             │            30 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_7 (Dense)                 │ (None, 10)             │           110 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_8 (Dense)                 │ (None, 1)              │            11 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 151 (604.00 B)

 Trainable params: 151 (604.00 B)

 Non-trainable params: 0 (0.00 B)

In [ ]:
# for checking which is faster
# model.compile(loss = 'binary_crossentropy', metrics = ['accuracy'])
# start = time.time()
# history = model.fit(X_train, Y_train, epochs = 10, batch_size = 320)

# if batch size is equal to the no. of datapoints or rows in your dataset so it is batcg gd and if it is 1 then it is stochastic gd

# print(time.time() - start)

Epoch 1/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 1s 909ms/step - accuracy: 0.3469 - loss: 13801.7266
Epoch 2/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 45ms/step - accuracy: 0.3469 - loss: 12932.8232
Epoch 3/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 47ms/step - accuracy: 0.3469 - loss: 12312.8594
Epoch 4/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 45ms/step - accuracy: 0.3469 - loss: 11799.7158
Epoch 5/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 44ms/step - accuracy: 0.3469 - loss: 11348.4678
Epoch 6/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 48ms/step - accuracy: 0.3469 - loss: 10938.3164
Epoch 7/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 68ms/step - accuracy: 0.3469 - loss: 10557.6904
Epoch 8/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 48ms/step - accuracy: 0.3469 - loss: 10199.4043
Epoch 9/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 46ms/step - accuracy: 0.3469 - loss: 9858.6465
Epoch 10/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 49ms/step - accuracy: 0.3469 - loss: 9532.0283
1.4955155849456787

In [ ]:
# for checking which is faster
# model.compile(loss = 'binary_crossentropy', metrics = ['accuracy'])
# start = time.time()
# history = model.fit(X_train, Y_train, epochs = 10, batch_size = 1)

# if batch size is equal to the no. of datapoints or rows in your dataset so it is batcg gd and if it is 1 then it is stochastic gd

# print(time.time() - start)

Epoch 1/10
320/320 ━━━━━━━━━━━━━━━━━━━━ 7s 8ms/step - accuracy: 0.4531 - loss: 701.4667
Epoch 2/10
320/320 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.4781 - loss: 115.4572
Epoch 3/10
320/320 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.5000 - loss: 117.8097
Epoch 4/10
320/320 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.4938 - loss: 114.4114
Epoch 5/10
320/320 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.5312 - loss: 108.3941
Epoch 6/10
320/320 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.5094 - loss: 100.7576
Epoch 7/10
320/320 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.5594 - loss: 97.2385
Epoch 8/10
320/320 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.5594 - loss: 94.0064
Epoch 9/10
320/320 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.5375 - loss: 101.0983
Epoch 10/10
320/320 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.5562 - loss: 91.9497
14.05681562423706

In [ ]:
# for checking which converges faster batch gd

model.compile(loss = 'binary_crossentropy', metrics = ['accuracy'])
history = model.fit(X_scaled, Y, epochs = 10, batch_size = 400, validation_split = 0.2)

Epoch 1/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 1s 954ms/step - accuracy: 0.7594 - loss: 0.5967 - val_accuracy: 0.4750 - val_loss: 0.7660
Epoch 2/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 101ms/step - accuracy: 0.7688 - loss: 0.5895 - val_accuracy: 0.4750 - val_loss: 0.7638
Epoch 3/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 93ms/step - accuracy: 0.7750 - loss: 0.5843 - val_accuracy: 0.4875 - val_loss: 0.7621
Epoch 4/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 93ms/step - accuracy: 0.7781 - loss: 0.5801 - val_accuracy: 0.5000 - val_loss: 0.7606
Epoch 5/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 99ms/step - accuracy: 0.7781 - loss: 0.5763 - val_accuracy: 0.5125 - val_loss: 0.7593
Epoch 6/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 92ms/step - accuracy: 0.7781 - loss: 0.5728 - val_accuracy: 0.5125 - val_loss: 0.7580
Epoch 7/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 92ms/step - accuracy: 0.7781 - loss: 0.5694 - val_accuracy: 0.5125 - val_loss: 0.7567
Epoch 8/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 97ms/step - accuracy: 0.7781 - loss: 0.5663 - val_accuracy: 0.5125 - val_loss: 0.7554
Epoch 9/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 107ms/step - accuracy: 0.7750 - loss: 0.5632 - val_accuracy: 0.5125 - val_loss: 0.7542
Epoch 10/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 109ms/step - accuracy: 0.7750 - loss: 0.5603 - val_accuracy: 0.5250 - val_loss: 0.7529

In [ ]:
# for checking which converges faster stochastic gd

model.compile(loss = 'binary_crossentropy', metrics = ['accuracy'])
history = model.fit(X_scaled, Y, epochs = 10, batch_size = 1, validation_split = 0.2)

Epoch 1/10
320/320 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - accuracy: 0.7937 - loss: 0.4570 - val_accuracy: 0.6000 - val_loss: 0.6635
Epoch 2/10
320/320 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8281 - loss: 0.3538 - val_accuracy: 0.6500 - val_loss: 0.5677
Epoch 3/10
320/320 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.8188 - loss: 0.3256 - val_accuracy: 0.6875 - val_loss: 0.5061
Epoch 4/10
320/320 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8313 - loss: 0.3125 - val_accuracy: 0.7250 - val_loss: 0.4690
Epoch 5/10
320/320 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8469 - loss: 0.3103 - val_accuracy: 0.7750 - val_loss: 0.4352
Epoch 6/10
320/320 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.8562 - loss: 0.3091 - val_accuracy: 0.7750 - val_loss: 0.4039
Epoch 7/10
320/320 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.8594 - loss: 0.3044 - val_accuracy: 0.8125 - val_loss: 0.3834
Epoch 8/10
320/320 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.8594 - loss: 0.3011 - val_accuracy: 0.8625 - val_loss: 0.3681
Epoch 9/10
320/320 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.8687 - loss: 0.2979 - val_accuracy: 0.8750 - val_loss: 0.3560
Epoch 10/10
320/320 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.8625 - loss: 0.3027 - val_accuracy: 0.8750 - val_loss: 0.3439