<a href="https://colab.research.google.com/github/mathuraryan036-collab/DL-GOOGLE-COLAB/blob/main/26_Keras_Tuner_Hyperparameter_Tuning.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [48]:
import numpy as np
import pandas as pd

In [49]:
 df = pd.read_csv('/content/diabetes.csv')

In [50]:
df.head()

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
0,6,148,72.0,35,169.5,33.6,0.627,50,1
1,1,85,66.0,29,102.5,26.6,0.351,31,0
2,8,183,64.0,32,169.5,23.3,0.672,32,1
3,1,89,66.0,23,94.0,28.1,0.167,21,0
4,0,137,40.0,35,168.0,43.1,2.288,33,1

In [51]:
df.corr()['Outcome']

Pregnancies                 0.221898
Glucose                     0.495990
BloodPressure               0.174469
SkinThickness               0.295138
Insulin                     0.377081
BMI                         0.315577
DiabetesPedigreeFunction    0.173844
Age                         0.238356
Outcome                     1.000000
Name: Outcome, dtype: float64

In [52]:
x = df.iloc[:, :-1].values
y = df.iloc[:,-1].values

In [53]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
x = scaler.fit_transform(x)

In [54]:
x

array([[ 0.63994726,  0.86462486, -0.03218035, ...,  0.16948251,
         0.46849198,  1.4259954 ],
       [-0.84488505, -1.20472661, -0.52812374, ..., -0.84854874,
        -0.36506078, -0.19067191],
       [ 1.23388019,  2.01426457, -0.69343821, ..., -1.32847775,
         0.60439732, -0.10558415],
       ...,
       [ 0.3429808 , -0.02224005, -0.03218035, ..., -0.90672195,
        -0.68519336, -0.27575966],
       [-0.84488505,  0.14199419, -1.02406713, ..., -0.33953311,
        -0.37110101,  1.17073215],
       [-0.84488505, -0.94195182, -0.19749482, ..., -0.2959032 ,
        -0.47378505, -0.87137393]])

In [55]:
x.shape

(768, 8)

In [56]:
from sklearn.model_selection import train_test_split

In [57]:
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=1)

In [138]:
import tensorflow
from tensorflow import keras
from keras import Sequential
from keras.layers import Dense, Dropout

In [59]:
model= Sequential()

model.add(Dense(32, activation = 'relu', input_dim = 8))
model.add(Dense(1, activation = 'sigmoid'))

model.compile(optimizer = 'Adam', loss = 'binary_crossentropy', metrics = ['accuracy'])

/usr/local/lib/python3.13/dist-packages/keras/src/layers/core/dense.py:106: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

In [60]:
model.summary()

Model: "sequential_1"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense_2 (Dense)                 │ (None, 32)             │           288 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_3 (Dense)                 │ (None, 1)              │            33 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 321 (1.25 KB)

 Trainable params: 321 (1.25 KB)

 Non-trainable params: 0 (0.00 B)

In [61]:
model.fit(x_train, y_train, batch_size = 32, epochs = 10, validation_data = (x_test, y_test))

Epoch 1/10
20/20 ━━━━━━━━━━━━━━━━━━━━ 2s 18ms/step - accuracy: 0.5065 - loss: 0.7305 - val_accuracy: 0.6299 - val_loss: 0.6884
Epoch 2/10
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6384 - loss: 0.6602 - val_accuracy: 0.6753 - val_loss: 0.6204
Epoch 3/10
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.6971 - loss: 0.6074 - val_accuracy: 0.7338 - val_loss: 0.5691
Epoch 4/10
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - accuracy: 0.7264 - loss: 0.5681 - val_accuracy: 0.7597 - val_loss: 0.5299
Epoch 5/10
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - accuracy: 0.7590 - loss: 0.5360 - val_accuracy: 0.7662 - val_loss: 0.4982
Epoch 6/10
20/20 ━━━━━━━━━━━━━━━━━━━━ 1s 21ms/step - accuracy: 0.7752 - loss: 0.5112 - val_accuracy: 0.7922 - val_loss: 0.4729
Epoch 7/10
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - accuracy: 0.7915 - loss: 0.4905 - val_accuracy: 0.8117 - val_loss: 0.4532
Epoch 8/10
20/20 ━━━━━━━━━━━━━━━━━━━━ 1s 42ms/step - accuracy: 0.7980 - loss: 0.4738 - val_accuracy: 0.8312 - val_loss: 0.4363
Epoch 9/10
20/20 ━━━━━━━━━━━━━━━━━━━━ 1s 31ms/step - accuracy: 0.8029 - loss: 0.4600 - val_accuracy: 0.8506 - val_loss: 0.4233
Epoch 10/10
20/20 ━━━━━━━━━━━━━━━━━━━━ 1s 28ms/step - accuracy: 0.8062 - loss: 0.4471 - val_accuracy: 0.8571 - val_loss: 0.4126

1. how to select appropriate optimizer

In [62]:
!pip install keras-tuner

Requirement already satisfied: keras-tuner in /usr/local/lib/python3.13/dist-packages (1.4.8)
Requirement already satisfied: keras in /usr/local/lib/python3.13/dist-packages (from keras-tuner) (3.13.2)
Requirement already satisfied: packaging in /usr/local/lib/python3.13/dist-packages (from keras-tuner) (26.3)
Requirement already satisfied: requests in /usr/local/lib/python3.13/dist-packages (from keras-tuner) (2.32.4)
Requirement already satisfied: kt-legacy in /usr/local/lib/python3.13/dist-packages (from keras-tuner) (1.0.5)
Requirement already satisfied: grpcio in /usr/local/lib/python3.13/dist-packages (from keras-tuner) (1.83.1)
Requirement already satisfied: protobuf in /usr/local/lib/python3.13/dist-packages (from keras-tuner) (5.29.6)
Requirement already satisfied: typing-extensions~=4.12 in /usr/local/lib/python3.13/dist-packages (from grpcio->keras-tuner) (4.16.0)
Requirement already satisfied: absl-py in /usr/local/lib/python3.13/dist-packages (from keras->keras-tuner) (1.4.0)
Requirement already satisfied: numpy in /usr/local/lib/python3.13/dist-packages (from keras->keras-tuner) (2.1.3)
Requirement already satisfied: rich in /usr/local/lib/python3.13/dist-packages (from keras->keras-tuner) (13.9.4)
Requirement already satisfied: namex in /usr/local/lib/python3.13/dist-packages (from keras->keras-tuner) (0.1.0)
Requirement already satisfied: h5py in /usr/local/lib/python3.13/dist-packages (from keras->keras-tuner) (3.16.0)
Requirement already satisfied: optree in /usr/local/lib/python3.13/dist-packages (from keras->keras-tuner) (0.20.0)
Requirement already satisfied: ml-dtypes in /usr/local/lib/python3.13/dist-packages (from keras->keras-tuner) (0.6.0)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.13/dist-packages (from requests->keras-tuner) (3.4.9)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.13/dist-packages (from requests->keras-tuner) (3.19)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.13/dist-packages (from requests->keras-tuner) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.13/dist-packages (from requests->keras-tuner) (2026.7.22)
Requirement already satisfied: markdown-it-py>=2.2.0 in /usr/local/lib/python3.13/dist-packages (from rich->keras->keras-tuner) (4.2.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in /usr/local/lib/python3.13/dist-packages (from rich->keras->keras-tuner) (2.21.0)
Requirement already satisfied: mdurl~=0.1 in /usr/local/lib/python3.13/dist-packages (from markdown-it-py>=2.2.0->rich->keras->keras-tuner) (0.1.2)

In [63]:
import keras_tuner as kt

In [64]:
def build_model(hp): # hp stands for hyperparameter

  model = Sequential()

  model.add(Dense(32, activation = 'relu', input_dim = 8))
  model.add(Dense(1, activation = 'sigmoid'))

  optimizer = hp.Choice('optimizer', values = ['adam', 'sgd', 'rmsprop', 'adadelta'])

  model.compile(optimizer = optimizer, loss = 'binary_crossentropy', metrics = ['accuracy'])

  return model

In [80]:
import IPython

IPython.display.clear_output = lambda *args, **kwargs: None

In [81]:
tuner = kt.RandomSearch(build_model, objective = 'val_accuracy', max_trials = 5, overwrite = True)

In [82]:
tuner.search(x_train, y_train, epochs = 5, validation_data = (x_test, y_test), verbose = 2)

Search: Running Trial #1

Value             |Best Value So Far |Hyperparameter
adam              |adam              |optimizer

Epoch 1/5
20/20 - 1s - 62ms/step - accuracy: 0.4658 - loss: 0.7478 - val_accuracy: 0.5649 - val_loss: 0.6940
Epoch 2/5
20/20 - 0s - 8ms/step - accuracy: 0.6026 - loss: 0.6635 - val_accuracy: 0.6623 - val_loss: 0.6277
Epoch 3/5
20/20 - 0s - 9ms/step - accuracy: 0.6726 - loss: 0.6098 - val_accuracy: 0.7013 - val_loss: 0.5798
Epoch 4/5
20/20 - 0s - 9ms/step - accuracy: 0.6971 - loss: 0.5708 - val_accuracy: 0.7468 - val_loss: 0.5449
Epoch 5/5
20/20 - 0s - 8ms/step - accuracy: 0.7199 - loss: 0.5409 - val_accuracy: 0.7662 - val_loss: 0.5176
Trial 1 Complete [00h 00m 03s]
val_accuracy: 0.7662337422370911

Best val_accuracy So Far: 0.7662337422370911
Total elapsed time: 00h 00m 03s

Search: Running Trial #2

Value             |Best Value So Far |Hyperparameter
adadelta          |adam              |optimizer

Epoch 1/5
20/20 - 1s - 67ms/step - accuracy: 0.3795 - loss: 0.7761 - val_accuracy: 0.3766 - val_loss: 0.7520
Epoch 2/5
20/20 - 0s - 8ms/step - accuracy: 0.3795 - loss: 0.7760 - val_accuracy: 0.3766 - val_loss: 0.7519
Epoch 3/5
20/20 - 0s - 10ms/step - accuracy: 0.3795 - loss: 0.7759 - val_accuracy: 0.3766 - val_loss: 0.7518
Epoch 4/5
20/20 - 0s - 8ms/step - accuracy: 0.3795 - loss: 0.7757 - val_accuracy: 0.3766 - val_loss: 0.7516
Epoch 5/5
20/20 - 0s - 8ms/step - accuracy: 0.3795 - loss: 0.7756 - val_accuracy: 0.3766 - val_loss: 0.7515
Trial 2 Complete [00h 00m 03s]
val_accuracy: 0.37662336230278015

Best val_accuracy So Far: 0.7662337422370911
Total elapsed time: 00h 00m 06s

Search: Running Trial #3

Value             |Best Value So Far |Hyperparameter
sgd               |adam              |optimizer

Epoch 1/5
20/20 - 1s - 45ms/step - accuracy: 0.6498 - loss: 0.6971 - val_accuracy: 0.6429 - val_loss: 0.7161
Epoch 2/5
20/20 - 0s - 7ms/step - accuracy: 0.6515 - loss: 0.6588 - val_accuracy: 0.6429 - val_loss: 0.6735
Epoch 3/5
20/20 - 0s - 7ms/step - accuracy: 0.6531 - loss: 0.6268 - val_accuracy: 0.6429 - val_loss: 0.6379
Epoch 4/5
20/20 - 0s - 10ms/step - accuracy: 0.6531 - loss: 0.6002 - val_accuracy: 0.6494 - val_loss: 0.6087
Epoch 5/5
20/20 - 0s - 12ms/step - accuracy: 0.6547 - loss: 0.5784 - val_accuracy: 0.6623 - val_loss: 0.5846
Trial 3 Complete [00h 00m 03s]
val_accuracy: 0.6623376607894897

Best val_accuracy So Far: 0.7662337422370911
Total elapsed time: 00h 00m 09s

Search: Running Trial #4

Value             |Best Value So Far |Hyperparameter
rmsprop           |adam              |optimizer

Epoch 1/5
20/20 - 2s - 86ms/step - accuracy: 0.4186 - loss: 0.7675 - val_accuracy: 0.5455 - val_loss: 0.7078
Epoch 2/5
20/20 - 0s - 16ms/step - accuracy: 0.6059 - loss: 0.6750 - val_accuracy: 0.6299 - val_loss: 0.6386
Epoch 3/5
20/20 - 0s - 11ms/step - accuracy: 0.7003 - loss: 0.6140 - val_accuracy: 0.7143 - val_loss: 0.5851
Epoch 4/5
20/20 - 0s - 11ms/step - accuracy: 0.7280 - loss: 0.5675 - val_accuracy: 0.7468 - val_loss: 0.5445
Epoch 5/5
20/20 - 0s - 11ms/step - accuracy: 0.7476 - loss: 0.5326 - val_accuracy: 0.7792 - val_loss: 0.5124
Trial 4 Complete [00h 00m 04s]
val_accuracy: 0.7792207598686218

Best val_accuracy So Far: 0.7792207598686218
Total elapsed time: 00h 00m 13s

In [83]:
tuner.results_summary()

Results summary
Results in ./untitled_project
Showing 10 best trials
Objective(name="val_accuracy", direction="max")

Trial 3 summary
Hyperparameters:
optimizer: rmsprop
Score: 0.7792207598686218

Trial 0 summary
Hyperparameters:
optimizer: adam
Score: 0.7662337422370911

Trial 2 summary
Hyperparameters:
optimizer: sgd
Score: 0.6623376607894897

Trial 1 summary
Hyperparameters:
optimizer: adadelta
Score: 0.37662336230278015

In [84]:
tuner.results_summary(num_trials = 1)

Results summary
Results in ./untitled_project
Showing 1 best trials
Objective(name="val_accuracy", direction="max")

Trial 3 summary
Hyperparameters:
optimizer: rmsprop
Score: 0.7792207598686218

In [85]:
tuner.get_best_hyperparameters()[0].values

{'optimizer': 'rmsprop'}

In [86]:
model = tuner.get_best_models(num_models = 1)[0]

In [87]:
model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense (Dense)                   │ (None, 32)             │           288 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_1 (Dense)                 │ (None, 1)              │            33 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 321 (1.25 KB)

 Trainable params: 321 (1.25 KB)

 Non-trainable params: 0 (0.00 B)

In [88]:
model.fit(x_train, y_train, batch_size = 100, epochs = 100, initial_epoch = 6, validation_data = (x_test, y_test))

Epoch 7/100
7/7 ━━━━━━━━━━━━━━━━━━━━ 1s 40ms/step - accuracy: 0.7638 - loss: 0.5077 - val_accuracy: 0.7987 - val_loss: 0.4901
Epoch 8/100
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - accuracy: 0.7769 - loss: 0.4934 - val_accuracy: 0.7987 - val_loss: 0.4782
Epoch 9/100
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.7834 - loss: 0.4837 - val_accuracy: 0.7987 - val_loss: 0.4688
Epoch 10/100
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.7818 - loss: 0.4761 - val_accuracy: 0.8052 - val_loss: 0.4607
Epoch 11/100
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 0.7801 - loss: 0.4699 - val_accuracy: 0.8182 - val_loss: 0.4546
Epoch 12/100
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.7769 - loss: 0.4644 - val_accuracy: 0.8247 - val_loss: 0.4484
Epoch 13/100
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.7769 - loss: 0.4594 - val_accuracy: 0.8247 - val_loss: 0.4421
Epoch 14/100
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 0.7801 - loss: 0.4543 - val_accuracy: 0.8247 - val_loss: 0.4371
Epoch 15/100
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.7818 - loss: 0.4505 - val_accuracy: 0.8182 - val_loss: 0.4324
Epoch 16/100
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.7818 - loss: 0.4467 - val_accuracy: 0.8247 - val_loss: 0.4286
Epoch 17/100
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 0.7834 - loss: 0.4435 - val_accuracy: 0.8182 - val_loss: 0.4251
Epoch 18/100
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.7850 - loss: 0.4409 - val_accuracy: 0.8117 - val_loss: 0.4215
Epoch 19/100
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.7883 - loss: 0.4381 - val_accuracy: 0.8052 - val_loss: 0.4191
Epoch 20/100
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 0.7866 - loss: 0.4357 - val_accuracy: 0.8052 - val_loss: 0.4181
Epoch 21/100
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.7932 - loss: 0.4336 - val_accuracy: 0.8182 - val_loss: 0.4156
Epoch 22/100
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 0.7948 - loss: 0.4312 - val_accuracy: 0.8247 - val_loss: 0.4132
Epoch 23/100
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 0.7964 - loss: 0.4292 - val_accuracy: 0.8312 - val_loss: 0.4115
Epoch 24/100
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.7980 - loss: 0.4271 - val_accuracy: 0.8247 - val_loss: 0.4101
Epoch 25/100
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 0.7997 - loss: 0.4253 - val_accuracy: 0.8312 - val_loss: 0.4083
Epoch 26/100
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 0.7997 - loss: 0.4235 - val_accuracy: 0.8312 - val_loss: 0.4070
Epoch 27/100
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.7997 - loss: 0.4220 - val_accuracy: 0.8377 - val_loss: 0.4048
Epoch 28/100
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.7980 - loss: 0.4205 - val_accuracy: 0.8312 - val_loss: 0.4034
Epoch 29/100
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.8029 - loss: 0.4189 - val_accuracy: 0.8182 - val_loss: 0.4010
Epoch 30/100
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.8013 - loss: 0.4175 - val_accuracy: 0.8247 - val_loss: 0.3995
Epoch 31/100
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 0.8013 - loss: 0.4163 - val_accuracy: 0.8247 - val_loss: 0.3992
Epoch 32/100
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.8029 - loss: 0.4151 - val_accuracy: 0.8312 - val_loss: 0.3988
Epoch 33/100
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.7980 - loss: 0.4142 - val_accuracy: 0.8247 - val_loss: 0.3977
Epoch 34/100
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.7997 - loss: 0.4130 - val_accuracy: 0.8312 - val_loss: 0.3966
Epoch 35/100
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - accuracy: 0.8029 - loss: 0.4116 - val_accuracy: 0.8312 - val_loss: 0.3954
Epoch 36/100
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - accuracy: 0.8029 - loss: 0.4103 - val_accuracy: 0.8117 - val_loss: 0.3947
Epoch 37/100
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - accuracy: 0.7997 - loss: 0.4092 - val_accuracy: 0.8182 - val_loss: 0.3938
Epoch 38/100
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - accuracy: 0.7997 - loss: 0.4081 - val_accuracy: 0.8182 - val_loss: 0.3931
Epoch 39/100
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - accuracy: 0.8013 - loss: 0.4070 - val_accuracy: 0.8312 - val_loss: 0.3926
Epoch 40/100
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - accuracy: 0.8013 - loss: 0.4059 - val_accuracy: 0.8182 - val_loss: 0.3913
Epoch 41/100
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - accuracy: 0.8013 - loss: 0.4048 - val_accuracy: 0.8182 - val_loss: 0.3909
Epoch 42/100
7/7 ━━━━━━━━━━━━━━━━━━━━ 1s 109ms/step - accuracy: 0.8013 - loss: 0.4035 - val_accuracy: 0.8182 - val_loss: 0.3895
Epoch 43/100
7/7 ━━━━━━━━━━━━━━━━━━━━ 1s 108ms/step - accuracy: 0.7997 - loss: 0.4026 - val_accuracy: 0.8247 - val_loss: 0.3889
Epoch 44/100
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - accuracy: 0.8013 - loss: 0.4014 - val_accuracy: 0.8247 - val_loss: 0.3888
Epoch 45/100
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - accuracy: 0.8046 - loss: 0.4004 - val_accuracy: 0.8247 - val_loss: 0.3877
Epoch 46/100
7/7 ━━━━━━━━━━━━━━━━━━━━ 1s 56ms/step - accuracy: 0.8046 - loss: 0.3994 - val_accuracy: 0.8247 - val_loss: 0.3873
Epoch 47/100
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - accuracy: 0.8046 - loss: 0.3983 - val_accuracy: 0.8247 - val_loss: 0.3867
Epoch 48/100
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - accuracy: 0.8029 - loss: 0.3971 - val_accuracy: 0.8247 - val_loss: 0.3852
Epoch 49/100
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 0.8046 - loss: 0.3958 - val_accuracy: 0.8247 - val_loss: 0.3854
Epoch 50/100
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - accuracy: 0.8062 - loss: 0.3949 - val_accuracy: 0.8312 - val_loss: 0.3848
Epoch 51/100
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 0.8046 - loss: 0.3939 - val_accuracy: 0.8247 - val_loss: 0.3836
Epoch 52/100
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - accuracy: 0.8029 - loss: 0.3932 - val_accuracy: 0.8312 - val_loss: 0.3831
Epoch 53/100
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 0.7997 - loss: 0.3920 - val_accuracy: 0.8247 - val_loss: 0.3825
Epoch 54/100
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - accuracy: 0.8094 - loss: 0.3908 - val_accuracy: 0.8312 - val_loss: 0.3817
Epoch 55/100
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 0.8062 - loss: 0.3897 - val_accuracy: 0.8312 - val_loss: 0.3813
Epoch 56/100
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 0.8078 - loss: 0.3886 - val_accuracy: 0.8312 - val_loss: 0.3800
Epoch 57/100
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.8094 - loss: 0.3876 - val_accuracy: 0.8377 - val_loss: 0.3795
Epoch 58/100
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 0.8029 - loss: 0.3865 - val_accuracy: 0.8247 - val_loss: 0.3790
Epoch 59/100
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 0.8094 - loss: 0.3856 - val_accuracy: 0.8312 - val_loss: 0.3783
Epoch 60/100
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - accuracy: 0.8111 - loss: 0.3847 - val_accuracy: 0.8312 - val_loss: 0.3777
Epoch 61/100
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 0.8160 - loss: 0.3835 - val_accuracy: 0.8312 - val_loss: 0.3769
Epoch 62/100
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - accuracy: 0.8160 - loss: 0.3823 - val_accuracy: 0.8312 - val_loss: 0.3751
Epoch 63/100
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.8160 - loss: 0.3817 - val_accuracy: 0.8247 - val_loss: 0.3751
Epoch 64/100
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 0.8160 - loss: 0.3803 - val_accuracy: 0.8312 - val_loss: 0.3751
Epoch 65/100
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 0.8176 - loss: 0.3793 - val_accuracy: 0.8377 - val_loss: 0.3740
Epoch 66/100
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - accuracy: 0.8192 - loss: 0.3784 - val_accuracy: 0.8312 - val_loss: 0.3731
Epoch 67/100
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - accuracy: 0.8176 - loss: 0.3772 - val_accuracy: 0.8377 - val_loss: 0.3723
Epoch 68/100
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.8176 - loss: 0.3759 - val_accuracy: 0.8442 - val_loss: 0.3715
Epoch 69/100
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 0.8208 - loss: 0.3747 - val_accuracy: 0.8377 - val_loss: 0.3718
Epoch 70/100
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 0.8208 - loss: 0.3734 - val_accuracy: 0.8442 - val_loss: 0.3717
Epoch 71/100
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.8241 - loss: 0.3727 - val_accuracy: 0.8571 - val_loss: 0.3713
Epoch 72/100
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.8241 - loss: 0.3715 - val_accuracy: 0.8571 - val_loss: 0.3704
Epoch 73/100
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - accuracy: 0.8274 - loss: 0.3704 - val_accuracy: 0.8571 - val_loss: 0.3703
Epoch 74/100
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.8290 - loss: 0.3692 - val_accuracy: 0.8571 - val_loss: 0.3693
Epoch 75/100
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 0.8322 - loss: 0.3677 - val_accuracy: 0.8636 - val_loss: 0.3695
Epoch 76/100
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - accuracy: 0.8355 - loss: 0.3665 - val_accuracy: 0.8636 - val_loss: 0.3689
Epoch 77/100
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.8371 - loss: 0.3652 - val_accuracy: 0.8636 - val_loss: 0.3689
Epoch 78/100
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 0.8404 - loss: 0.3641 - val_accuracy: 0.8636 - val_loss: 0.3682
Epoch 79/100
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.8371 - loss: 0.3629 - val_accuracy: 0.8636 - val_loss: 0.3676
Epoch 80/100
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 0.8355 - loss: 0.3616 - val_accuracy: 0.8636 - val_loss: 0.3666
Epoch 81/100
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.8388 - loss: 0.3607 - val_accuracy: 0.8571 - val_loss: 0.3657
Epoch 82/100
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.8404 - loss: 0.3596 - val_accuracy: 0.8636 - val_loss: 0.3659
Epoch 83/100
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.8453 - loss: 0.3584 - val_accuracy: 0.8636 - val_loss: 0.3655
Epoch 84/100
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.8436 - loss: 0.3576 - val_accuracy: 0.8636 - val_loss: 0.3642
Epoch 85/100
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.8453 - loss: 0.3564 - val_accuracy: 0.8571 - val_loss: 0.3622
Epoch 86/100
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.8453 - loss: 0.3556 - val_accuracy: 0.8636 - val_loss: 0.3627
Epoch 87/100
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.8502 - loss: 0.3544 - val_accuracy: 0.8636 - val_loss: 0.3632
Epoch 88/100
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.8485 - loss: 0.3535 - val_accuracy: 0.8636 - val_loss: 0.3626
Epoch 89/100
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.8534 - loss: 0.3522 - val_accuracy: 0.8636 - val_loss: 0.3623
Epoch 90/100
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.8518 - loss: 0.3512 - val_accuracy: 0.8636 - val_loss: 0.3606
Epoch 91/100
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.8534 - loss: 0.3502 - val_accuracy: 0.8571 - val_loss: 0.3602
Epoch 92/100
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.8534 - loss: 0.3492 - val_accuracy: 0.8571 - val_loss: 0.3598
Epoch 93/100
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.8518 - loss: 0.3483 - val_accuracy: 0.8571 - val_loss: 0.3589
Epoch 94/100
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.8567 - loss: 0.3474 - val_accuracy: 0.8571 - val_loss: 0.3584
Epoch 95/100
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - accuracy: 0.8534 - loss: 0.3464 - val_accuracy: 0.8636 - val_loss: 0.3577
Epoch 96/100
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - accuracy: 0.8550 - loss: 0.3454 - val_accuracy: 0.8571 - val_loss: 0.3582
Epoch 97/100
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 0.8567 - loss: 0.3447 - val_accuracy: 0.8506 - val_loss: 0.3575
Epoch 98/100
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 0.8567 - loss: 0.3440 - val_accuracy: 0.8571 - val_loss: 0.3573
Epoch 99/100
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.8567 - loss: 0.3429 - val_accuracy: 0.8571 - val_loss: 0.3581
Epoch 100/100
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.8583 - loss: 0.3420 - val_accuracy: 0.8506 - val_loss: 0.3575

2. no. of nodes in a layer

In [104]:
def build_model(hp):

  model = Sequential()

  units = hp.Int('units', min_value = 8, max_value = 128)

  model.add(Dense(units = units, activation = 'relu', input_dim = 8))
  model.add(Dense(1, activation = 'sigmoid'))

  model.compile(optimizer = 'rmsprop', loss = 'binary_crossentropy', metrics = ['accuracy'])

  return model

In [107]:
tuner = kt.RandomSearch(build_model, objective = 'val_accuracy', max_trials = 5, directory = 'mydir', overwrite = True)

/usr/local/lib/python3.13/dist-packages/keras/src/layers/core/dense.py:106: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

In [108]:
tuner.search(x_train, y_train, epochs = 5, validation_data = (x_test, y_test), verbose = 2)

Search: Running Trial #1

Value             |Best Value So Far |Hyperparameter
109               |109               |units

Epoch 1/5
20/20 - 2s - 78ms/step - accuracy: 0.6612 - loss: 0.6052 - val_accuracy: 0.7597 - val_loss: 0.5247
Epoch 2/5
20/20 - 0s - 8ms/step - accuracy: 0.7492 - loss: 0.5225 - val_accuracy: 0.7792 - val_loss: 0.4726
Epoch 3/5
20/20 - 0s - 7ms/step - accuracy: 0.7606 - loss: 0.4851 - val_accuracy: 0.8052 - val_loss: 0.4446
Epoch 4/5
20/20 - 0s - 8ms/step - accuracy: 0.7687 - loss: 0.4614 - val_accuracy: 0.8117 - val_loss: 0.4228
Epoch 5/5
20/20 - 0s - 8ms/step - accuracy: 0.7785 - loss: 0.4461 - val_accuracy: 0.8247 - val_loss: 0.4094
Trial 1 Complete [00h 00m 03s]
val_accuracy: 0.8246753215789795

Best val_accuracy So Far: 0.8246753215789795
Total elapsed time: 00h 00m 03s

Search: Running Trial #2

Value             |Best Value So Far |Hyperparameter
105               |109               |units

Epoch 1/5
20/20 - 1s - 48ms/step - accuracy: 0.6759 - loss: 0.6285 - val_accuracy: 0.8117 - val_loss: 0.5448
Epoch 2/5
20/20 - 0s - 7ms/step - accuracy: 0.7557 - loss: 0.5360 - val_accuracy: 0.8247 - val_loss: 0.4808
Epoch 3/5
20/20 - 0s - 7ms/step - accuracy: 0.7704 - loss: 0.4908 - val_accuracy: 0.8182 - val_loss: 0.4428
Epoch 4/5
20/20 - 0s - 7ms/step - accuracy: 0.7720 - loss: 0.4648 - val_accuracy: 0.8182 - val_loss: 0.4226
Epoch 5/5
20/20 - 0s - 8ms/step - accuracy: 0.7801 - loss: 0.4500 - val_accuracy: 0.8182 - val_loss: 0.4062
Trial 2 Complete [00h 00m 03s]
val_accuracy: 0.8246753215789795

Best val_accuracy So Far: 0.8246753215789795
Total elapsed time: 00h 00m 06s

Search: Running Trial #3

Value             |Best Value So Far |Hyperparameter
128               |109               |units

Epoch 1/5
20/20 - 1s - 69ms/step - accuracy: 0.7606 - loss: 0.5538 - val_accuracy: 0.8117 - val_loss: 0.4816
Epoch 2/5
20/20 - 0s - 13ms/step - accuracy: 0.7883 - loss: 0.4774 - val_accuracy: 0.8117 - val_loss: 0.4318
Epoch 3/5
20/20 - 0s - 15ms/step - accuracy: 0.7964 - loss: 0.4468 - val_accuracy: 0.8247 - val_loss: 0.4064
Epoch 4/5
20/20 - 0s - 9ms/step - accuracy: 0.7980 - loss: 0.4317 - val_accuracy: 0.8312 - val_loss: 0.3924
Epoch 5/5
20/20 - 0s - 7ms/step - accuracy: 0.8046 - loss: 0.4205 - val_accuracy: 0.8182 - val_loss: 0.3832
Trial 3 Complete [00h 00m 03s]
val_accuracy: 0.8311688303947449

Best val_accuracy So Far: 0.8311688303947449
Total elapsed time: 00h 00m 10s

Search: Running Trial #4

Value             |Best Value So Far |Hyperparameter
11                |128               |units

Epoch 1/5
20/20 - 1s - 49ms/step - accuracy: 0.6498 - loss: 0.6354 - val_accuracy: 0.6429 - val_loss: 0.6152
Epoch 2/5
20/20 - 0s - 22ms/step - accuracy: 0.6645 - loss: 0.6060 - val_accuracy: 0.6753 - val_loss: 0.5872
Epoch 3/5
20/20 - 0s - 7ms/step - accuracy: 0.6906 - loss: 0.5838 - val_accuracy: 0.7078 - val_loss: 0.5642
Epoch 4/5
20/20 - 0s - 8ms/step - accuracy: 0.6922 - loss: 0.5664 - val_accuracy: 0.7208 - val_loss: 0.5440
Epoch 5/5
20/20 - 0s - 8ms/step - accuracy: 0.7052 - loss: 0.5505 - val_accuracy: 0.7532 - val_loss: 0.5258
Trial 4 Complete [00h 00m 03s]
val_accuracy: 0.7532467246055603

Best val_accuracy So Far: 0.8311688303947449
Total elapsed time: 00h 00m 12s

Search: Running Trial #5

Value             |Best Value So Far |Hyperparameter
82                |128               |units

Epoch 1/5
20/20 - 1s - 49ms/step - accuracy: 0.5993 - loss: 0.6426 - val_accuracy: 0.7143 - val_loss: 0.5742
Epoch 2/5
20/20 - 0s - 8ms/step - accuracy: 0.7345 - loss: 0.5467 - val_accuracy: 0.7597 - val_loss: 0.5092
Epoch 3/5
20/20 - 0s - 8ms/step - accuracy: 0.7655 - loss: 0.5000 - val_accuracy: 0.7987 - val_loss: 0.4719
Epoch 4/5
20/20 - 0s - 9ms/step - accuracy: 0.7801 - loss: 0.4718 - val_accuracy: 0.8182 - val_loss: 0.4450
Epoch 5/5
20/20 - 0s - 7ms/step - accuracy: 0.7834 - loss: 0.4531 - val_accuracy: 0.8117 - val_loss: 0.4258
Trial 5 Complete [00h 00m 03s]
val_accuracy: 0.8181818127632141

Best val_accuracy So Far: 0.8311688303947449
Total elapsed time: 00h 00m 15s

In [110]:
tuner.results_summary()

Results summary
Results in mydir/untitled_project
Showing 10 best trials
Objective(name="val_accuracy", direction="max")

Trial 2 summary
Hyperparameters:
units: 128
Score: 0.8311688303947449

Trial 0 summary
Hyperparameters:
units: 109
Score: 0.8246753215789795

Trial 1 summary
Hyperparameters:
units: 105
Score: 0.8246753215789795

Trial 4 summary
Hyperparameters:
units: 82
Score: 0.8181818127632141

Trial 3 summary
Hyperparameters:
units: 11
Score: 0.7532467246055603

In [109]:
tuner.get_best_hyperparameters()[0].values

{'units': 128}

In [111]:
model = tuner.get_best_models(num_models = 1)[0]

/usr/local/lib/python3.13/dist-packages/keras/src/layers/core/dense.py:106: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)
/usr/local/lib/python3.13/dist-packages/keras/src/saving/saving_lib.py:797: UserWarning: Skipping variable loading for optimizer 'rmsprop', because it has 2 variables whereas the saved optimizer has 6 variables.
  saveable.load_own_variables(weights_store.get(inner_path))

In [112]:
model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense (Dense)                   │ (None, 128)            │         1,152 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_1 (Dense)                 │ (None, 1)              │           129 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 1,281 (5.00 KB)

 Trainable params: 1,281 (5.00 KB)

 Non-trainable params: 0 (0.00 B)

In [103]:
model.fit(x_train, y_train, batch_size = 100, epochs = 100, initial_epoch = 6, validation_data = (x_test, y_test))

Epoch 7/100
7/7 ━━━━━━━━━━━━━━━━━━━━ 2s 89ms/step - accuracy: 0.7671 - loss: 0.5265 - val_accuracy: 0.8247 - val_loss: 0.4797
Epoch 8/100
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 45ms/step - accuracy: 0.7687 - loss: 0.4955 - val_accuracy: 0.8247 - val_loss: 0.4590
Epoch 9/100
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 27ms/step - accuracy: 0.7769 - loss: 0.4816 - val_accuracy: 0.8182 - val_loss: 0.4452
Epoch 10/100
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 0.7801 - loss: 0.4705 - val_accuracy: 0.8117 - val_loss: 0.4339
Epoch 11/100
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 0.7785 - loss: 0.4619 - val_accuracy: 0.8247 - val_loss: 0.4233
Epoch 12/100
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 0.7769 - loss: 0.4550 - val_accuracy: 0.8247 - val_loss: 0.4169
Epoch 13/100
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - accuracy: 0.7834 - loss: 0.4490 - val_accuracy: 0.8182 - val_loss: 0.4109
Epoch 14/100
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - accuracy: 0.7915 - loss: 0.4442 - val_accuracy: 0.8247 - val_loss: 0.4067
Epoch 15/100
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 0.7915 - loss: 0.4394 - val_accuracy: 0.8247 - val_loss: 0.4049
Epoch 16/100
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 0.7964 - loss: 0.4363 - val_accuracy: 0.8312 - val_loss: 0.3992
Epoch 17/100
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - accuracy: 0.7883 - loss: 0.4326 - val_accuracy: 0.8312 - val_loss: 0.3949
Epoch 18/100
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 0.7997 - loss: 0.4296 - val_accuracy: 0.8312 - val_loss: 0.3922
Epoch 19/100
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - accuracy: 0.7964 - loss: 0.4264 - val_accuracy: 0.8312 - val_loss: 0.3890
Epoch 20/100
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - accuracy: 0.7980 - loss: 0.4233 - val_accuracy: 0.8377 - val_loss: 0.3869
Epoch 21/100
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - accuracy: 0.7964 - loss: 0.4207 - val_accuracy: 0.8377 - val_loss: 0.3833
Epoch 22/100
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 0.7980 - loss: 0.4179 - val_accuracy: 0.8377 - val_loss: 0.3809
Epoch 23/100
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 0.8046 - loss: 0.4153 - val_accuracy: 0.8377 - val_loss: 0.3788
Epoch 24/100
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - accuracy: 0.8029 - loss: 0.4130 - val_accuracy: 0.8442 - val_loss: 0.3760
Epoch 25/100
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 0.8013 - loss: 0.4105 - val_accuracy: 0.8442 - val_loss: 0.3754
Epoch 26/100
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.8013 - loss: 0.4085 - val_accuracy: 0.8506 - val_loss: 0.3738
Epoch 27/100
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 0.8013 - loss: 0.4061 - val_accuracy: 0.8377 - val_loss: 0.3714
Epoch 28/100
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.8013 - loss: 0.4036 - val_accuracy: 0.8377 - val_loss: 0.3718
Epoch 29/100
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - accuracy: 0.8078 - loss: 0.4019 - val_accuracy: 0.8442 - val_loss: 0.3709
Epoch 30/100
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - accuracy: 0.8094 - loss: 0.3991 - val_accuracy: 0.8442 - val_loss: 0.3678
Epoch 31/100
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 0.8078 - loss: 0.3973 - val_accuracy: 0.8506 - val_loss: 0.3652
Epoch 32/100
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 0.8127 - loss: 0.3949 - val_accuracy: 0.8442 - val_loss: 0.3648
Epoch 33/100
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - accuracy: 0.8094 - loss: 0.3928 - val_accuracy: 0.8442 - val_loss: 0.3637
Epoch 34/100
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.8143 - loss: 0.3901 - val_accuracy: 0.8442 - val_loss: 0.3624
Epoch 35/100
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 0.8127 - loss: 0.3881 - val_accuracy: 0.8442 - val_loss: 0.3602
Epoch 36/100
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 0.8160 - loss: 0.3861 - val_accuracy: 0.8442 - val_loss: 0.3598
Epoch 37/100
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.8160 - loss: 0.3843 - val_accuracy: 0.8442 - val_loss: 0.3592
Epoch 38/100
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.8225 - loss: 0.3819 - val_accuracy: 0.8442 - val_loss: 0.3586
Epoch 39/100
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - accuracy: 0.8225 - loss: 0.3799 - val_accuracy: 0.8377 - val_loss: 0.3565
Epoch 40/100
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.8225 - loss: 0.3786 - val_accuracy: 0.8442 - val_loss: 0.3553
Epoch 41/100
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 0.8241 - loss: 0.3767 - val_accuracy: 0.8506 - val_loss: 0.3553
Epoch 42/100
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 0.8290 - loss: 0.3741 - val_accuracy: 0.8506 - val_loss: 0.3529
Epoch 43/100
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.8290 - loss: 0.3723 - val_accuracy: 0.8506 - val_loss: 0.3523
Epoch 44/100
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 0.8241 - loss: 0.3708 - val_accuracy: 0.8571 - val_loss: 0.3532
Epoch 45/100
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.8339 - loss: 0.3683 - val_accuracy: 0.8506 - val_loss: 0.3537
Epoch 46/100
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.8355 - loss: 0.3668 - val_accuracy: 0.8571 - val_loss: 0.3538
Epoch 47/100
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.8420 - loss: 0.3650 - val_accuracy: 0.8506 - val_loss: 0.3507
Epoch 48/100
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - accuracy: 0.8355 - loss: 0.3636 - val_accuracy: 0.8506 - val_loss: 0.3502
Epoch 49/100
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 0.8371 - loss: 0.3617 - val_accuracy: 0.8571 - val_loss: 0.3494
Epoch 50/100
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.8371 - loss: 0.3600 - val_accuracy: 0.8571 - val_loss: 0.3481
Epoch 51/100
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - accuracy: 0.8436 - loss: 0.3585 - val_accuracy: 0.8571 - val_loss: 0.3469
Epoch 52/100
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.8420 - loss: 0.3567 - val_accuracy: 0.8571 - val_loss: 0.3463
Epoch 53/100
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.8436 - loss: 0.3546 - val_accuracy: 0.8506 - val_loss: 0.3448
Epoch 54/100
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 0.8420 - loss: 0.3527 - val_accuracy: 0.8571 - val_loss: 0.3439
Epoch 55/100
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.8436 - loss: 0.3505 - val_accuracy: 0.8571 - val_loss: 0.3438
Epoch 56/100
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 0.8502 - loss: 0.3495 - val_accuracy: 0.8636 - val_loss: 0.3426
Epoch 57/100
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - accuracy: 0.8599 - loss: 0.3476 - val_accuracy: 0.8571 - val_loss: 0.3411
Epoch 58/100
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 0.8518 - loss: 0.3466 - val_accuracy: 0.8571 - val_loss: 0.3396
Epoch 59/100
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 0.8518 - loss: 0.3444 - val_accuracy: 0.8571 - val_loss: 0.3376
Epoch 60/100
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.8518 - loss: 0.3431 - val_accuracy: 0.8571 - val_loss: 0.3376
Epoch 61/100
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - accuracy: 0.8567 - loss: 0.3413 - val_accuracy: 0.8571 - val_loss: 0.3361
Epoch 62/100
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 26ms/step - accuracy: 0.8599 - loss: 0.3400 - val_accuracy: 0.8701 - val_loss: 0.3335
Epoch 63/100
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - accuracy: 0.8599 - loss: 0.3379 - val_accuracy: 0.8636 - val_loss: 0.3329
Epoch 64/100
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - accuracy: 0.8632 - loss: 0.3361 - val_accuracy: 0.8636 - val_loss: 0.3326
Epoch 65/100
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 27ms/step - accuracy: 0.8632 - loss: 0.3352 - val_accuracy: 0.8701 - val_loss: 0.3312
Epoch 66/100
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - accuracy: 0.8664 - loss: 0.3336 - val_accuracy: 0.8701 - val_loss: 0.3306
Epoch 67/100
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 22ms/step - accuracy: 0.8648 - loss: 0.3324 - val_accuracy: 0.8701 - val_loss: 0.3312
Epoch 68/100
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - accuracy: 0.8681 - loss: 0.3309 - val_accuracy: 0.8701 - val_loss: 0.3299
Epoch 69/100
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 28ms/step - accuracy: 0.8746 - loss: 0.3297 - val_accuracy: 0.8766 - val_loss: 0.3303
Epoch 70/100
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 22ms/step - accuracy: 0.8811 - loss: 0.3286 - val_accuracy: 0.8766 - val_loss: 0.3308
Epoch 71/100
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - accuracy: 0.8746 - loss: 0.3271 - val_accuracy: 0.8701 - val_loss: 0.3312
Epoch 72/100
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - accuracy: 0.8827 - loss: 0.3268 - val_accuracy: 0.8766 - val_loss: 0.3331
Epoch 73/100
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 22ms/step - accuracy: 0.8844 - loss: 0.3244 - val_accuracy: 0.8766 - val_loss: 0.3322
Epoch 74/100
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - accuracy: 0.8860 - loss: 0.3235 - val_accuracy: 0.8636 - val_loss: 0.3316
Epoch 75/100
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - accuracy: 0.8876 - loss: 0.3224 - val_accuracy: 0.8766 - val_loss: 0.3311
Epoch 76/100
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 0.8827 - loss: 0.3208 - val_accuracy: 0.8701 - val_loss: 0.3315
Epoch 77/100
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - accuracy: 0.8909 - loss: 0.3201 - val_accuracy: 0.8766 - val_loss: 0.3299
Epoch 78/100
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - accuracy: 0.8909 - loss: 0.3186 - val_accuracy: 0.8701 - val_loss: 0.3306
Epoch 79/100
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - accuracy: 0.8876 - loss: 0.3179 - val_accuracy: 0.8701 - val_loss: 0.3301
Epoch 80/100
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - accuracy: 0.8893 - loss: 0.3168 - val_accuracy: 0.8766 - val_loss: 0.3304
Epoch 81/100
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - accuracy: 0.8909 - loss: 0.3158 - val_accuracy: 0.8701 - val_loss: 0.3298
Epoch 82/100
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - accuracy: 0.8893 - loss: 0.3152 - val_accuracy: 0.8636 - val_loss: 0.3290
Epoch 83/100
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - accuracy: 0.8909 - loss: 0.3140 - val_accuracy: 0.8701 - val_loss: 0.3295
Epoch 84/100
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - accuracy: 0.8876 - loss: 0.3130 - val_accuracy: 0.8636 - val_loss: 0.3304
Epoch 85/100
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - accuracy: 0.8876 - loss: 0.3121 - val_accuracy: 0.8636 - val_loss: 0.3322
Epoch 86/100
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - accuracy: 0.8893 - loss: 0.3108 - val_accuracy: 0.8701 - val_loss: 0.3324
Epoch 87/100
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 0.8909 - loss: 0.3103 - val_accuracy: 0.8766 - val_loss: 0.3316
Epoch 88/100
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - accuracy: 0.8893 - loss: 0.3095 - val_accuracy: 0.8636 - val_loss: 0.3319
Epoch 89/100
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - accuracy: 0.8909 - loss: 0.3080 - val_accuracy: 0.8571 - val_loss: 0.3322
Epoch 90/100
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - accuracy: 0.8893 - loss: 0.3075 - val_accuracy: 0.8571 - val_loss: 0.3317
Epoch 91/100
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.8925 - loss: 0.3077 - val_accuracy: 0.8701 - val_loss: 0.3317
Epoch 92/100
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 0.8909 - loss: 0.3060 - val_accuracy: 0.8701 - val_loss: 0.3315
Epoch 93/100
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - accuracy: 0.8941 - loss: 0.3055 - val_accuracy: 0.8701 - val_loss: 0.3297
Epoch 94/100
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - accuracy: 0.8909 - loss: 0.3050 - val_accuracy: 0.8701 - val_loss: 0.3329
Epoch 95/100
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.8941 - loss: 0.3045 - val_accuracy: 0.8701 - val_loss: 0.3379
Epoch 96/100
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.8925 - loss: 0.3037 - val_accuracy: 0.8701 - val_loss: 0.3355
Epoch 97/100
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 0.8941 - loss: 0.3030 - val_accuracy: 0.8701 - val_loss: 0.3353
Epoch 98/100
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.8925 - loss: 0.3025 - val_accuracy: 0.8701 - val_loss: 0.3350
Epoch 99/100
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - accuracy: 0.8909 - loss: 0.3026 - val_accuracy: 0.8701 - val_loss: 0.3320
Epoch 100/100
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 0.8958 - loss: 0.3016 - val_accuracy: 0.8701 - val_loss: 0.3310

3. how to select no. of layer

In [117]:
def build_model(hp):

  model = Sequential()

  model.add(Dense(72, activation = 'relu', input_dim = 8))

  for i in range(hp.Int('num_layers', min_value = 1, max_value = 10)):

    model.add(Dense(72,activation = 'relu'))

  model.add(Dense(1, activation = 'sigmoid'))

  model.compile(optimizer = 'rmsprop', loss = 'binary_crossentropy', metrics = ['accuracy'])

  return model

In [118]:
tuner = kt.RandomSearch(build_model, objective = 'val_accuracy', max_trials = 3, directory = 'mydir', overwrite = True)

In [119]:
tuner.search(x_train, y_train, epochs = 5, validation_data = (x_test, y_test), verbose = 2)

Search: Running Trial #1

Value             |Best Value So Far |Hyperparameter
6                 |6                 |num_layers

/usr/local/lib/python3.13/dist-packages/keras/src/layers/core/dense.py:106: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

Epoch 1/5
20/20 - 3s - 166ms/step - accuracy: 0.6987 - loss: 0.5516 - val_accuracy: 0.7792 - val_loss: 0.4527
Epoch 2/5
20/20 - 0s - 11ms/step - accuracy: 0.8143 - loss: 0.4312 - val_accuracy: 0.8442 - val_loss: 0.3657
Epoch 3/5
20/20 - 0s - 13ms/step - accuracy: 0.8241 - loss: 0.3958 - val_accuracy: 0.8506 - val_loss: 0.3586
Epoch 4/5
20/20 - 0s - 10ms/step - accuracy: 0.8502 - loss: 0.3632 - val_accuracy: 0.8182 - val_loss: 0.3785
Epoch 5/5
20/20 - 0s - 9ms/step - accuracy: 0.8485 - loss: 0.3586 - val_accuracy: 0.8442 - val_loss: 0.3610
Trial 1 Complete [00h 00m 07s]
val_accuracy: 0.850649356842041

Best val_accuracy So Far: 0.850649356842041
Total elapsed time: 00h 00m 07s

Search: Running Trial #2

Value             |Best Value So Far |Hyperparameter
4                 |6                 |num_layers

Epoch 1/5
20/20 - 2s - 88ms/step - accuracy: 0.7248 - loss: 0.5629 - val_accuracy: 0.8117 - val_loss: 0.4408
Epoch 2/5
20/20 - 0s - 12ms/step - accuracy: 0.7915 - loss: 0.4264 - val_accuracy: 0.8377 - val_loss: 0.4149
Epoch 3/5
20/20 - 0s - 14ms/step - accuracy: 0.8225 - loss: 0.3936 - val_accuracy: 0.8377 - val_loss: 0.3918
Epoch 4/5
20/20 - 0s - 17ms/step - accuracy: 0.8274 - loss: 0.3725 - val_accuracy: 0.8442 - val_loss: 0.3680
Epoch 5/5
20/20 - 0s - 17ms/step - accuracy: 0.8534 - loss: 0.3433 - val_accuracy: 0.8701 - val_loss: 0.3490
Trial 2 Complete [00h 00m 04s]
val_accuracy: 0.8701298832893372

Best val_accuracy So Far: 0.8701298832893372
Total elapsed time: 00h 00m 11s

Search: Running Trial #3

Value             |Best Value So Far |Hyperparameter
1                 |4                 |num_layers

/usr/local/lib/python3.13/dist-packages/keras/src/layers/core/dense.py:106: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

Epoch 1/5
20/20 - 1s - 69ms/step - accuracy: 0.7410 - loss: 0.5432 - val_accuracy: 0.8117 - val_loss: 0.4565
Epoch 2/5
20/20 - 0s - 8ms/step - accuracy: 0.7964 - loss: 0.4510 - val_accuracy: 0.8052 - val_loss: 0.4127
Epoch 3/5
20/20 - 0s - 10ms/step - accuracy: 0.7948 - loss: 0.4256 - val_accuracy: 0.8312 - val_loss: 0.3857
Epoch 4/5
20/20 - 0s - 8ms/step - accuracy: 0.8013 - loss: 0.4086 - val_accuracy: 0.8247 - val_loss: 0.3834
Epoch 5/5
20/20 - 0s - 10ms/step - accuracy: 0.8062 - loss: 0.3956 - val_accuracy: 0.8377 - val_loss: 0.3704
Trial 3 Complete [00h 00m 04s]
val_accuracy: 0.8376623392105103

Best val_accuracy So Far: 0.8701298832893372
Total elapsed time: 00h 00m 15s

In [120]:
tuner.results_summary()

Results summary
Results in mydir/untitled_project
Showing 10 best trials
Objective(name="val_accuracy", direction="max")

Trial 1 summary
Hyperparameters:
num_layers: 4
Score: 0.8701298832893372

Trial 0 summary
Hyperparameters:
num_layers: 6
Score: 0.850649356842041

Trial 2 summary
Hyperparameters:
num_layers: 1
Score: 0.8376623392105103

In [121]:
tuner.get_best_hyperparameters()[0].values

{'num_layers': 4}

In [123]:
model = tuner.get_best_models(num_models = 1)[0]

/usr/local/lib/python3.13/dist-packages/keras/src/layers/core/dense.py:106: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)
/usr/local/lib/python3.13/dist-packages/keras/src/saving/saving_lib.py:797: UserWarning: Skipping variable loading for optimizer 'rmsprop', because it has 2 variables whereas the saved optimizer has 14 variables.
  saveable.load_own_variables(weights_store.get(inner_path))

In [124]:
model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense (Dense)                   │ (None, 72)             │           648 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_1 (Dense)                 │ (None, 72)             │         5,256 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_2 (Dense)                 │ (None, 72)             │         5,256 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_3 (Dense)                 │ (None, 72)             │         5,256 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_4 (Dense)                 │ (None, 72)             │         5,256 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_5 (Dense)                 │ (None, 1)              │            73 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 21,745 (84.94 KB)

 Trainable params: 21,745 (84.94 KB)

 Non-trainable params: 0 (0.00 B)

In [127]:
model.fit(x_train, y_train, epochs = 100, initial_epoch = 6, validation_data = (x_test, y_test))

Epoch 7/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 2s 23ms/step - accuracy: 0.8599 - loss: 0.3342 - val_accuracy: 0.8636 - val_loss: 0.3516
Epoch 8/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.8860 - loss: 0.3016 - val_accuracy: 0.8442 - val_loss: 0.3696
Epoch 9/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.8860 - loss: 0.2949 - val_accuracy: 0.8442 - val_loss: 0.3529
Epoch 10/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8958 - loss: 0.2851 - val_accuracy: 0.8442 - val_loss: 0.3790
Epoch 11/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8974 - loss: 0.2723 - val_accuracy: 0.8182 - val_loss: 0.4077
Epoch 12/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9023 - loss: 0.2693 - val_accuracy: 0.8247 - val_loss: 0.3798
Epoch 13/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.9055 - loss: 0.2567 - val_accuracy: 0.8377 - val_loss: 0.4110
Epoch 14/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9137 - loss: 0.2514 - val_accuracy: 0.8117 - val_loss: 0.3707
Epoch 15/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9137 - loss: 0.2435 - val_accuracy: 0.8117 - val_loss: 0.4250
Epoch 16/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9072 - loss: 0.2372 - val_accuracy: 0.8377 - val_loss: 0.4374
Epoch 17/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9218 - loss: 0.2191 - val_accuracy: 0.8182 - val_loss: 0.4092
Epoch 18/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9316 - loss: 0.2085 - val_accuracy: 0.8442 - val_loss: 0.3949
Epoch 19/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.9267 - loss: 0.2046 - val_accuracy: 0.8442 - val_loss: 0.4266
Epoch 20/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.9397 - loss: 0.1908 - val_accuracy: 0.8312 - val_loss: 0.4534
Epoch 21/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9349 - loss: 0.1797 - val_accuracy: 0.7857 - val_loss: 0.4829
Epoch 22/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9332 - loss: 0.1761 - val_accuracy: 0.7922 - val_loss: 0.4720
Epoch 23/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9430 - loss: 0.1649 - val_accuracy: 0.8377 - val_loss: 0.4526
Epoch 24/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9430 - loss: 0.1575 - val_accuracy: 0.8636 - val_loss: 0.4279
Epoch 25/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.9479 - loss: 0.1458 - val_accuracy: 0.8117 - val_loss: 0.4945
Epoch 26/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.9528 - loss: 0.1286 - val_accuracy: 0.8247 - val_loss: 0.5010
Epoch 27/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.9479 - loss: 0.1342 - val_accuracy: 0.6948 - val_loss: 0.7830
Epoch 28/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.9609 - loss: 0.1145 - val_accuracy: 0.7468 - val_loss: 0.7011
Epoch 29/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.9674 - loss: 0.1062 - val_accuracy: 0.8182 - val_loss: 0.5580
Epoch 30/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.9658 - loss: 0.0898 - val_accuracy: 0.8377 - val_loss: 0.6348
Epoch 31/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.9674 - loss: 0.0953 - val_accuracy: 0.8052 - val_loss: 0.6441
Epoch 32/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9658 - loss: 0.0740 - val_accuracy: 0.7792 - val_loss: 0.7396
Epoch 33/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.9707 - loss: 0.0763 - val_accuracy: 0.7987 - val_loss: 0.7035
Epoch 34/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.9853 - loss: 0.0511 - val_accuracy: 0.8247 - val_loss: 0.7862
Epoch 35/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.9658 - loss: 0.0801 - val_accuracy: 0.7792 - val_loss: 0.7245
Epoch 36/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.9951 - loss: 0.0347 - val_accuracy: 0.7792 - val_loss: 0.9674
Epoch 37/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9837 - loss: 0.0498 - val_accuracy: 0.7792 - val_loss: 0.9489
Epoch 38/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9886 - loss: 0.0433 - val_accuracy: 0.7857 - val_loss: 0.8821
Epoch 39/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.9935 - loss: 0.0307 - val_accuracy: 0.7987 - val_loss: 0.9621
Epoch 40/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9788 - loss: 0.0621 - val_accuracy: 0.7857 - val_loss: 0.9788
Epoch 41/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 1.0000 - loss: 0.0141 - val_accuracy: 0.8247 - val_loss: 0.9474
Epoch 42/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.9870 - loss: 0.0337 - val_accuracy: 0.7987 - val_loss: 1.1867
Epoch 43/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.9821 - loss: 0.0422 - val_accuracy: 0.7597 - val_loss: 1.0669
Epoch 44/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.9919 - loss: 0.0280 - val_accuracy: 0.7922 - val_loss: 1.0076
Epoch 45/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 1.0000 - loss: 0.0067 - val_accuracy: 0.8052 - val_loss: 1.0639
Epoch 46/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.9853 - loss: 0.0655 - val_accuracy: 0.7792 - val_loss: 1.0928
Epoch 47/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 1.0000 - loss: 0.0092 - val_accuracy: 0.7987 - val_loss: 1.0795
Epoch 48/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.9853 - loss: 0.0476 - val_accuracy: 0.7727 - val_loss: 1.1896
Epoch 49/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 1.0000 - loss: 0.0046 - val_accuracy: 0.8182 - val_loss: 1.1259
Epoch 50/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.9935 - loss: 0.0231 - val_accuracy: 0.8247 - val_loss: 1.3174
Epoch 51/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.9886 - loss: 0.0230 - val_accuracy: 0.8182 - val_loss: 1.2513
Epoch 52/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.9984 - loss: 0.0093 - val_accuracy: 0.7792 - val_loss: 1.2885
Epoch 53/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - accuracy: 0.9902 - loss: 0.0353 - val_accuracy: 0.7857 - val_loss: 1.1752
Epoch 54/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 1.0000 - loss: 0.0041 - val_accuracy: 0.7857 - val_loss: 1.2517
Epoch 55/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9821 - loss: 0.0544 - val_accuracy: 0.8052 - val_loss: 1.2039
Epoch 56/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 1.0000 - loss: 0.0025 - val_accuracy: 0.7922 - val_loss: 1.2711
Epoch 57/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 1.0000 - loss: 0.0031 - val_accuracy: 0.8052 - val_loss: 1.4656
Epoch 58/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.9967 - loss: 0.0083 - val_accuracy: 0.7597 - val_loss: 1.5110
Epoch 59/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9886 - loss: 0.0302 - val_accuracy: 0.8052 - val_loss: 1.2480
Epoch 60/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.9902 - loss: 0.0198 - val_accuracy: 0.7922 - val_loss: 1.3281
Epoch 61/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 1.0000 - loss: 0.0017 - val_accuracy: 0.7727 - val_loss: 1.3693
Epoch 62/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 1.0000 - loss: 0.0011 - val_accuracy: 0.7792 - val_loss: 1.4603
Epoch 63/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9967 - loss: 0.0085 - val_accuracy: 0.7662 - val_loss: 1.7136
Epoch 64/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.9951 - loss: 0.0301 - val_accuracy: 0.8052 - val_loss: 1.6129
Epoch 65/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 1.0000 - loss: 0.0018 - val_accuracy: 0.8052 - val_loss: 1.4981
Epoch 66/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 1.0000 - loss: 0.0046 - val_accuracy: 0.7987 - val_loss: 1.5299
Epoch 67/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9984 - loss: 0.0132 - val_accuracy: 0.7987 - val_loss: 1.5279
Epoch 68/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9967 - loss: 0.0132 - val_accuracy: 0.7857 - val_loss: 1.7342
Epoch 69/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9935 - loss: 0.0396 - val_accuracy: 0.7792 - val_loss: 1.5334
Epoch 70/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 1.0000 - loss: 5.9154e-04 - val_accuracy: 0.7857 - val_loss: 1.5126
Epoch 71/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 1.0000 - loss: 9.4633e-04 - val_accuracy: 0.7922 - val_loss: 1.5390
Epoch 72/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9837 - loss: 0.0422 - val_accuracy: 0.7662 - val_loss: 1.6454
Epoch 73/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9951 - loss: 0.0076 - val_accuracy: 0.7727 - val_loss: 1.4958
Epoch 74/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9984 - loss: 0.0092 - val_accuracy: 0.7857 - val_loss: 1.4854
Epoch 75/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 1.0000 - loss: 6.8009e-04 - val_accuracy: 0.7857 - val_loss: 1.5400
Epoch 76/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9919 - loss: 0.0331 - val_accuracy: 0.8182 - val_loss: 1.5988
Epoch 77/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 1.0000 - loss: 0.0036 - val_accuracy: 0.7792 - val_loss: 1.6085
Epoch 78/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 1.0000 - loss: 0.0019 - val_accuracy: 0.7987 - val_loss: 1.5237
Epoch 79/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 1.0000 - loss: 2.2171e-04 - val_accuracy: 0.7857 - val_loss: 1.5651
Epoch 80/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 1.0000 - loss: 1.9160e-04 - val_accuracy: 0.7857 - val_loss: 1.5907
Epoch 81/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 1.0000 - loss: 1.6467e-04 - val_accuracy: 0.7597 - val_loss: 1.8584
Epoch 82/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 0.9788 - loss: 0.0747 - val_accuracy: 0.8052 - val_loss: 1.8887
Epoch 83/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 1s 21ms/step - accuracy: 1.0000 - loss: 4.6348e-04 - val_accuracy: 0.8052 - val_loss: 1.8400
Epoch 84/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 1.0000 - loss: 2.4581e-04 - val_accuracy: 0.7987 - val_loss: 1.8509
Epoch 85/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 1.0000 - loss: 1.7993e-04 - val_accuracy: 0.7987 - val_loss: 1.8081
Epoch 86/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 1.0000 - loss: 1.4036e-04 - val_accuracy: 0.7987 - val_loss: 1.7791
Epoch 87/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9935 - loss: 0.0156 - val_accuracy: 0.8506 - val_loss: 1.6897
Epoch 88/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9870 - loss: 0.0598 - val_accuracy: 0.7922 - val_loss: 1.8620
Epoch 89/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 1.0000 - loss: 5.3545e-04 - val_accuracy: 0.7987 - val_loss: 1.8003
Epoch 90/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 1.0000 - loss: 2.2876e-04 - val_accuracy: 0.7922 - val_loss: 1.8099
Epoch 91/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 1.0000 - loss: 1.5885e-04 - val_accuracy: 0.7987 - val_loss: 1.7760
Epoch 92/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 1.0000 - loss: 1.3977e-04 - val_accuracy: 0.7857 - val_loss: 1.9153
Epoch 93/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9837 - loss: 0.0729 - val_accuracy: 0.8182 - val_loss: 1.8354
Epoch 94/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.9951 - loss: 0.0106 - val_accuracy: 0.7727 - val_loss: 1.7342
Epoch 95/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 1.0000 - loss: 2.9584e-04 - val_accuracy: 0.7922 - val_loss: 1.7100
Epoch 96/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 1.0000 - loss: 1.7223e-04 - val_accuracy: 0.7922 - val_loss: 1.7063
Epoch 97/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 1.0000 - loss: 1.5834e-04 - val_accuracy: 0.7922 - val_loss: 1.7232
Epoch 98/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9870 - loss: 0.0759 - val_accuracy: 0.7857 - val_loss: 1.7809
Epoch 99/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 1.0000 - loss: 4.0090e-04 - val_accuracy: 0.8052 - val_loss: 1.7203
Epoch 100/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 1.0000 - loss: 1.3299e-04 - val_accuracy: 0.8117 - val_loss: 1.7098

4. all in all one model

In [140]:
def build_model(hp):

  model = Sequential()

  counter = 0

  for i in range(hp.Int('num_layers', min_value = 1, max_value = 10)):

    if counter == 0:

      model.add(
          Dense(
              hp.Int('units' + str(i), min_value = 8, max_value = 128, step = 8),
              activation = hp.Choice('activation' + str(i), values = ['relu', 'tanh', 'sigmoid']),
              input_dim = 8
              )
          )
    else:
      model.add(
          Dense(
              hp.Int('units' + str(i), min_value = 8, max_value = 128, step = 8),
              activation = hp.Choice('activation' + str(i), values = ['relu', 'tanh', 'sigmoid'])
              )
          )
    # Add dropout after each Dense layer
    model.add(Dropout(hp.Choice('dropout' + str(i), values = [0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9])))
    counter += 1

  model.add(Dense(1, activation = 'sigmoid'))

  model.compile(optimizer = hp.Choice('optimizer', values = ['adam', 'sgd', 'rmsprop','nadam', 'adadelta']), loss = 'binary_crossentropy', metrics = ['accuracy'])

  return model

In [141]:
tuner = kt.RandomSearch(build_model, objective = 'val_accuracy', max_trials = 5, directory = 'mydir', overwrite = True)

/usr/local/lib/python3.13/dist-packages/keras/src/layers/core/dense.py:106: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

In [142]:
tuner.search(x_train, y_train, epochs = 5, validation_data = (x_test, y_test), verbose = 2)

Search: Running Trial #1

Value             |Best Value So Far |Hyperparameter
4                 |4                 |num_layers
56                |56                |units0
tanh              |tanh              |activation0
0.5               |0.5               |dropout0
adam              |adam              |optimizer

Epoch 1/5
20/20 - 3s - 172ms/step - accuracy: 0.6629 - loss: 0.6179 - val_accuracy: 0.7922 - val_loss: 0.5796
Epoch 2/5
20/20 - 0s - 10ms/step - accuracy: 0.7052 - loss: 0.5641 - val_accuracy: 0.7987 - val_loss: 0.5179
Epoch 3/5
20/20 - 0s - 9ms/step - accuracy: 0.7199 - loss: 0.5360 - val_accuracy: 0.7922 - val_loss: 0.4837
Epoch 4/5
20/20 - 0s - 12ms/step - accuracy: 0.7296 - loss: 0.5118 - val_accuracy: 0.8052 - val_loss: 0.4602
Epoch 5/5
20/20 - 0s - 11ms/step - accuracy: 0.7394 - loss: 0.5010 - val_accuracy: 0.8247 - val_loss: 0.4457
Trial 1 Complete [00h 00m 06s]
val_accuracy: 0.8246753215789795

Best val_accuracy So Far: 0.8246753215789795
Total elapsed time: 00h 00m 06s

Search: Running Trial #2

Value             |Best Value So Far |Hyperparameter
3                 |4                 |num_layers
88                |56                |units0
relu              |tanh              |activation0
0.9               |0.5               |dropout0
rmsprop           |adam              |optimizer
64                |8                 |units1
tanh              |relu              |activation1
0.7               |0.1               |dropout1
120               |8                 |units2
sigmoid           |relu              |activation2
0.3               |0.1               |dropout2
112               |8                 |units3
sigmoid           |relu              |activation3
0.8               |0.1               |dropout3

Epoch 1/5
20/20 - 2s - 80ms/step - accuracy: 0.6303 - loss: 0.6721 - val_accuracy: 0.6429 - val_loss: 0.6022
Epoch 2/5
20/20 - 0s - 9ms/step - accuracy: 0.6336 - loss: 0.6567 - val_accuracy: 0.6429 - val_loss: 0.5758
Epoch 3/5
20/20 - 0s - 11ms/step - accuracy: 0.6661 - loss: 0.6302 - val_accuracy: 0.6558 - val_loss: 0.5521
Epoch 4/5
20/20 - 0s - 8ms/step - accuracy: 0.6694 - loss: 0.6224 - val_accuracy: 0.6558 - val_loss: 0.5327
Epoch 5/5
20/20 - 0s - 10ms/step - accuracy: 0.6564 - loss: 0.6298 - val_accuracy: 0.7792 - val_loss: 0.5047
Trial 2 Complete [00h 00m 04s]
val_accuracy: 0.7792207598686218

Best val_accuracy So Far: 0.8246753215789795
Total elapsed time: 00h 00m 09s

Search: Running Trial #3

Value             |Best Value So Far |Hyperparameter
9                 |4                 |num_layers
104               |56                |units0
tanh              |tanh              |activation0
0.1               |0.5               |dropout0
sgd               |adam              |optimizer
120               |8                 |units1
relu              |relu              |activation1
0.8               |0.1               |dropout1
40                |8                 |units2
sigmoid           |relu              |activation2
0.6               |0.1               |dropout2
40                |8                 |units3
sigmoid           |relu              |activation3
0.5               |0.1               |dropout3

/usr/local/lib/python3.13/dist-packages/keras/src/layers/core/dense.py:106: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

Epoch 1/5
20/20 - 2s - 94ms/step - accuracy: 0.6433 - loss: 0.6719 - val_accuracy: 0.6429 - val_loss: 0.6674
Epoch 2/5
20/20 - 0s - 8ms/step - accuracy: 0.6450 - loss: 0.6706 - val_accuracy: 0.6429 - val_loss: 0.6663
Epoch 3/5
20/20 - 0s - 8ms/step - accuracy: 0.6515 - loss: 0.6635 - val_accuracy: 0.6429 - val_loss: 0.6653
Epoch 4/5
20/20 - 0s - 8ms/step - accuracy: 0.6498 - loss: 0.6465 - val_accuracy: 0.6429 - val_loss: 0.6654
Epoch 5/5
20/20 - 0s - 8ms/step - accuracy: 0.6515 - loss: 0.6582 - val_accuracy: 0.6429 - val_loss: 0.6645
Trial 3 Complete [00h 00m 04s]
val_accuracy: 0.6428571343421936

Best val_accuracy So Far: 0.8246753215789795
Total elapsed time: 00h 00m 13s

Search: Running Trial #4

Value             |Best Value So Far |Hyperparameter
7                 |4                 |num_layers
64                |56                |units0
relu              |tanh              |activation0
0.2               |0.5               |dropout0
nadam             |adam              |optimizer
88                |8                 |units1
tanh              |relu              |activation1
0.3               |0.1               |dropout1
72                |8                 |units2
sigmoid           |relu              |activation2
0.4               |0.1               |dropout2
80                |8                 |units3
sigmoid           |relu              |activation3
0.9               |0.1               |dropout3
120               |None              |units4
tanh              |None              |activation4
0.6               |None              |dropout4
16                |None              |units5
tanh              |None              |activation5
0.2               |None              |dropout5
112               |None              |units6
relu              |None              |activation6
0.7               |None              |dropout6
104               |None              |units7
relu              |None              |activation7
0.3               |None              |dropout7
72                |None              |units8
sigmoid           |None              |activation8
0.5               |None              |dropout8

Epoch 1/5
20/20 - 5s - 262ms/step - accuracy: 0.5228 - loss: 0.7372 - val_accuracy: 0.6429 - val_loss: 0.6578
Epoch 2/5
20/20 - 0s - 9ms/step - accuracy: 0.5440 - loss: 0.7224 - val_accuracy: 0.6429 - val_loss: 0.6520
Epoch 3/5
20/20 - 0s - 9ms/step - accuracy: 0.5456 - loss: 0.7062 - val_accuracy: 0.6429 - val_loss: 0.6513
Epoch 4/5
20/20 - 0s - 9ms/step - accuracy: 0.5717 - loss: 0.6931 - val_accuracy: 0.6429 - val_loss: 0.6530
Epoch 5/5
20/20 - 0s - 10ms/step - accuracy: 0.5912 - loss: 0.7019 - val_accuracy: 0.6429 - val_loss: 0.6521
Trial 4 Complete [00h 00m 08s]
val_accuracy: 0.6428571343421936

Best val_accuracy So Far: 0.8246753215789795
Total elapsed time: 00h 00m 21s

Search: Running Trial #5

Value             |Best Value So Far |Hyperparameter
1                 |4                 |num_layers
64                |56                |units0
relu              |tanh              |activation0
0.6               |0.5               |dropout0
rmsprop           |adam              |optimizer
8                 |8                 |units1
sigmoid           |relu              |activation1
0.9               |0.1               |dropout1
96                |8                 |units2
relu              |relu              |activation2
0.2               |0.1               |dropout2
24                |8                 |units3
relu              |relu              |activation3
0.3               |0.1               |dropout3
24                |None              |units4
tanh              |None              |activation4
0.5               |None              |dropout4
128               |None              |units5
sigmoid           |None              |activation5
0.5               |None              |dropout5
40                |None              |units6
tanh              |None              |activation6
0.8               |None              |dropout6
16                |None              |units7
relu              |None              |activation7
0.3               |None              |dropout7
8                 |None              |units8
tanh              |None              |activation8
0.6               |None              |dropout8

Epoch 1/5
20/20 - 1s - 54ms/step - accuracy: 0.5717 - loss: 0.7042 - val_accuracy: 0.7208 - val_loss: 0.5917
Epoch 2/5
20/20 - 0s - 9ms/step - accuracy: 0.6531 - loss: 0.6092 - val_accuracy: 0.7727 - val_loss: 0.5353
Epoch 3/5
20/20 - 0s - 8ms/step - accuracy: 0.6987 - loss: 0.5535 - val_accuracy: 0.8247 - val_loss: 0.4961
Epoch 4/5
20/20 - 0s - 8ms/step - accuracy: 0.7020 - loss: 0.5597 - val_accuracy: 0.8182 - val_loss: 0.4690
Epoch 5/5
20/20 - 0s - 8ms/step - accuracy: 0.7704 - loss: 0.5016 - val_accuracy: 0.8442 - val_loss: 0.4484
Trial 5 Complete [00h 00m 03s]
val_accuracy: 0.8441558480262756

Best val_accuracy So Far: 0.8441558480262756
Total elapsed time: 00h 00m 24s

In [143]:
tuner.results_summary()

Results summary
Results in mydir/untitled_project
Showing 10 best trials
Objective(name="val_accuracy", direction="max")

Trial 4 summary
Hyperparameters:
num_layers: 1
units0: 64
activation0: relu
dropout0: 0.6
optimizer: rmsprop
units1: 8
activation1: sigmoid
dropout1: 0.9
units2: 96
activation2: relu
dropout2: 0.2
units3: 24
activation3: relu
dropout3: 0.3
units4: 24
activation4: tanh
dropout4: 0.5
units5: 128
activation5: sigmoid
dropout5: 0.5
units6: 40
activation6: tanh
dropout6: 0.8
units7: 16
activation7: relu
dropout7: 0.3
units8: 8
activation8: tanh
dropout8: 0.6
Score: 0.8441558480262756

Trial 0 summary
Hyperparameters:
num_layers: 4
units0: 56
activation0: tanh
dropout0: 0.5
optimizer: adam
units1: 8
activation1: relu
dropout1: 0.1
units2: 8
activation2: relu
dropout2: 0.1
units3: 8
activation3: relu
dropout3: 0.1
Score: 0.8246753215789795

Trial 1 summary
Hyperparameters:
num_layers: 3
units0: 88
activation0: relu
dropout0: 0.9
optimizer: rmsprop
units1: 64
activation1: tanh
dropout1: 0.7
units2: 120
activation2: sigmoid
dropout2: 0.3
units3: 112
activation3: sigmoid
dropout3: 0.8
Score: 0.7792207598686218

Trial 2 summary
Hyperparameters:
num_layers: 9
units0: 104
activation0: tanh
dropout0: 0.1
optimizer: sgd
units1: 120
activation1: relu
dropout1: 0.8
units2: 40
activation2: sigmoid
dropout2: 0.6
units3: 40
activation3: sigmoid
dropout3: 0.5
units4: 8
activation4: relu
dropout4: 0.1
units5: 8
activation5: relu
dropout5: 0.1
units6: 8
activation6: relu
dropout6: 0.1
units7: 8
activation7: relu
dropout7: 0.1
units8: 8
activation8: relu
dropout8: 0.1
Score: 0.6428571343421936

Trial 3 summary
Hyperparameters:
num_layers: 7
units0: 64
activation0: relu
dropout0: 0.2
optimizer: nadam
units1: 88
activation1: tanh
dropout1: 0.3
units2: 72
activation2: sigmoid
dropout2: 0.4
units3: 80
activation3: sigmoid
dropout3: 0.9
units4: 120
activation4: tanh
dropout4: 0.6
units5: 16
activation5: tanh
dropout5: 0.2
units6: 112
activation6: relu
dropout6: 0.7
units7: 104
activation7: relu
dropout7: 0.3
units8: 72
activation8: sigmoid
dropout8: 0.5
Score: 0.6428571343421936

In [144]:
tuner.get_best_hyperparameters()[0].values

{'num_layers': 1,
 'units0': 64,
 'activation0': 'relu',
 'dropout0': 0.6,
 'optimizer': 'rmsprop',
 'units1': 8,
 'activation1': 'sigmoid',
 'dropout1': 0.9,
 'units2': 96,
 'activation2': 'relu',
 'dropout2': 0.2,
 'units3': 24,
 'activation3': 'relu',
 'dropout3': 0.3,
 'units4': 24,
 'activation4': 'tanh',
 'dropout4': 0.5,
 'units5': 128,
 'activation5': 'sigmoid',
 'dropout5': 0.5,
 'units6': 40,
 'activation6': 'tanh',
 'dropout6': 0.8,
 'units7': 16,
 'activation7': 'relu',
 'dropout7': 0.3,
 'units8': 8,
 'activation8': 'tanh',
 'dropout8': 0.6}

In [145]:
model = tuner.get_best_models(num_models = 1)[0]

/usr/local/lib/python3.13/dist-packages/keras/src/saving/saving_lib.py:797: UserWarning: Skipping variable loading for optimizer 'rmsprop', because it has 2 variables whereas the saved optimizer has 6 variables.
  saveable.load_own_variables(weights_store.get(inner_path))

In [146]:
model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense (Dense)                   │ (None, 64)             │           576 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout (Dropout)               │ (None, 64)             │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_1 (Dense)                 │ (None, 1)              │            65 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 641 (2.50 KB)

 Trainable params: 641 (2.50 KB)

 Non-trainable params: 0 (0.00 B)

In [147]:
model.fit(x_train, y_train, epochs = 200, initial_epoch = 6, validation_data = (x_test, y_test))

Epoch 7/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 1s 16ms/step - accuracy: 0.7638 - loss: 0.4796 - val_accuracy: 0.8312 - val_loss: 0.4287
Epoch 8/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7606 - loss: 0.4877 - val_accuracy: 0.8506 - val_loss: 0.4195
Epoch 9/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7736 - loss: 0.4768 - val_accuracy: 0.8442 - val_loss: 0.4113
Epoch 10/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7573 - loss: 0.4702 - val_accuracy: 0.8506 - val_loss: 0.4052
Epoch 11/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7655 - loss: 0.4782 - val_accuracy: 0.8442 - val_loss: 0.4010
Epoch 12/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7801 - loss: 0.4616 - val_accuracy: 0.8506 - val_loss: 0.3966
Epoch 13/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7785 - loss: 0.4596 - val_accuracy: 0.8442 - val_loss: 0.3930
Epoch 14/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7818 - loss: 0.4550 - val_accuracy: 0.8442 - val_loss: 0.3894
Epoch 15/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7883 - loss: 0.4474 - val_accuracy: 0.8506 - val_loss: 0.3860
Epoch 16/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7704 - loss: 0.4612 - val_accuracy: 0.8506 - val_loss: 0.3844
Epoch 17/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7850 - loss: 0.4584 - val_accuracy: 0.8571 - val_loss: 0.3819
Epoch 18/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7980 - loss: 0.4408 - val_accuracy: 0.8571 - val_loss: 0.3802
Epoch 19/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7899 - loss: 0.4504 - val_accuracy: 0.8571 - val_loss: 0.3787
Epoch 20/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8029 - loss: 0.4297 - val_accuracy: 0.8506 - val_loss: 0.3762
Epoch 21/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7866 - loss: 0.4425 - val_accuracy: 0.8506 - val_loss: 0.3745
Epoch 22/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7932 - loss: 0.4332 - val_accuracy: 0.8506 - val_loss: 0.3727
Epoch 23/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7980 - loss: 0.4192 - val_accuracy: 0.8506 - val_loss: 0.3707
Epoch 24/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7980 - loss: 0.4178 - val_accuracy: 0.8506 - val_loss: 0.3692
Epoch 25/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.7899 - loss: 0.4183 - val_accuracy: 0.8506 - val_loss: 0.3684
Epoch 26/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.8046 - loss: 0.4437 - val_accuracy: 0.8506 - val_loss: 0.3673
Epoch 27/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.8013 - loss: 0.4281 - val_accuracy: 0.8442 - val_loss: 0.3663
Epoch 28/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.7980 - loss: 0.4199 - val_accuracy: 0.8506 - val_loss: 0.3644
Epoch 29/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.8013 - loss: 0.4197 - val_accuracy: 0.8571 - val_loss: 0.3626
Epoch 30/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.8127 - loss: 0.4254 - val_accuracy: 0.8506 - val_loss: 0.3616
Epoch 31/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.8192 - loss: 0.4058 - val_accuracy: 0.8506 - val_loss: 0.3608
Epoch 32/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.8208 - loss: 0.4000 - val_accuracy: 0.8506 - val_loss: 0.3596
Epoch 33/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.8225 - loss: 0.4095 - val_accuracy: 0.8506 - val_loss: 0.3590
Epoch 34/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.8127 - loss: 0.3995 - val_accuracy: 0.8506 - val_loss: 0.3583
Epoch 35/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.8225 - loss: 0.4083 - val_accuracy: 0.8506 - val_loss: 0.3575
Epoch 36/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8208 - loss: 0.3887 - val_accuracy: 0.8506 - val_loss: 0.3567
Epoch 37/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8127 - loss: 0.3972 - val_accuracy: 0.8571 - val_loss: 0.3557
Epoch 38/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8355 - loss: 0.3908 - val_accuracy: 0.8571 - val_loss: 0.3547
Epoch 39/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8143 - loss: 0.4026 - val_accuracy: 0.8571 - val_loss: 0.3533
Epoch 40/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8306 - loss: 0.4046 - val_accuracy: 0.8442 - val_loss: 0.3519
Epoch 41/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8550 - loss: 0.3757 - val_accuracy: 0.8442 - val_loss: 0.3503
Epoch 42/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8371 - loss: 0.3829 - val_accuracy: 0.8571 - val_loss: 0.3496
Epoch 43/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8208 - loss: 0.4185 - val_accuracy: 0.8571 - val_loss: 0.3504
Epoch 44/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8208 - loss: 0.3932 - val_accuracy: 0.8636 - val_loss: 0.3499
Epoch 45/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8225 - loss: 0.4006 - val_accuracy: 0.8636 - val_loss: 0.3507
Epoch 46/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8192 - loss: 0.3976 - val_accuracy: 0.8571 - val_loss: 0.3508
Epoch 47/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8339 - loss: 0.3888 - val_accuracy: 0.8506 - val_loss: 0.3503
Epoch 48/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8274 - loss: 0.3918 - val_accuracy: 0.8506 - val_loss: 0.3500
Epoch 49/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8322 - loss: 0.3840 - val_accuracy: 0.8571 - val_loss: 0.3508
Epoch 50/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8290 - loss: 0.3792 - val_accuracy: 0.8506 - val_loss: 0.3492
Epoch 51/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8453 - loss: 0.3817 - val_accuracy: 0.8506 - val_loss: 0.3487
Epoch 52/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8306 - loss: 0.3894 - val_accuracy: 0.8571 - val_loss: 0.3492
Epoch 53/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8339 - loss: 0.3849 - val_accuracy: 0.8506 - val_loss: 0.3493
Epoch 54/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8469 - loss: 0.3833 - val_accuracy: 0.8571 - val_loss: 0.3490
Epoch 55/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8371 - loss: 0.3834 - val_accuracy: 0.8636 - val_loss: 0.3475
Epoch 56/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8420 - loss: 0.3821 - val_accuracy: 0.8701 - val_loss: 0.3464
Epoch 57/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.8518 - loss: 0.3752 - val_accuracy: 0.8701 - val_loss: 0.3460
Epoch 58/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8567 - loss: 0.3659 - val_accuracy: 0.8701 - val_loss: 0.3454
Epoch 59/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8518 - loss: 0.3856 - val_accuracy: 0.8701 - val_loss: 0.3446
Epoch 60/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8404 - loss: 0.3716 - val_accuracy: 0.8701 - val_loss: 0.3434
Epoch 61/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8469 - loss: 0.3818 - val_accuracy: 0.8701 - val_loss: 0.3438
Epoch 62/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8518 - loss: 0.3517 - val_accuracy: 0.8701 - val_loss: 0.3438
Epoch 63/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8306 - loss: 0.3715 - val_accuracy: 0.8701 - val_loss: 0.3432
Epoch 64/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8453 - loss: 0.3736 - val_accuracy: 0.8701 - val_loss: 0.3427
Epoch 65/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8469 - loss: 0.3751 - val_accuracy: 0.8701 - val_loss: 0.3426
Epoch 66/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8420 - loss: 0.3781 - val_accuracy: 0.8636 - val_loss: 0.3420
Epoch 67/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8436 - loss: 0.3659 - val_accuracy: 0.8636 - val_loss: 0.3418
Epoch 68/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8518 - loss: 0.3717 - val_accuracy: 0.8636 - val_loss: 0.3415
Epoch 69/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8518 - loss: 0.3658 - val_accuracy: 0.8636 - val_loss: 0.3425
Epoch 70/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8567 - loss: 0.3572 - val_accuracy: 0.8636 - val_loss: 0.3430
Epoch 71/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8502 - loss: 0.3637 - val_accuracy: 0.8571 - val_loss: 0.3440
Epoch 72/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8599 - loss: 0.3693 - val_accuracy: 0.8571 - val_loss: 0.3430
Epoch 73/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8371 - loss: 0.3668 - val_accuracy: 0.8506 - val_loss: 0.3448
Epoch 74/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8518 - loss: 0.3683 - val_accuracy: 0.8506 - val_loss: 0.3443
Epoch 75/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8502 - loss: 0.3629 - val_accuracy: 0.8506 - val_loss: 0.3443
Epoch 76/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8616 - loss: 0.3522 - val_accuracy: 0.8506 - val_loss: 0.3448
Epoch 77/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8469 - loss: 0.3609 - val_accuracy: 0.8506 - val_loss: 0.3435
Epoch 78/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8453 - loss: 0.3718 - val_accuracy: 0.8506 - val_loss: 0.3439
Epoch 79/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8469 - loss: 0.3660 - val_accuracy: 0.8506 - val_loss: 0.3443
Epoch 80/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8664 - loss: 0.3574 - val_accuracy: 0.8506 - val_loss: 0.3442
Epoch 81/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8616 - loss: 0.3583 - val_accuracy: 0.8506 - val_loss: 0.3447
Epoch 82/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8583 - loss: 0.3613 - val_accuracy: 0.8506 - val_loss: 0.3459
Epoch 83/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8681 - loss: 0.3409 - val_accuracy: 0.8506 - val_loss: 0.3453
Epoch 84/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8681 - loss: 0.3514 - val_accuracy: 0.8506 - val_loss: 0.3452
Epoch 85/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.8713 - loss: 0.3621 - val_accuracy: 0.8506 - val_loss: 0.3443
Epoch 86/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8599 - loss: 0.3593 - val_accuracy: 0.8506 - val_loss: 0.3442
Epoch 87/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8632 - loss: 0.3524 - val_accuracy: 0.8506 - val_loss: 0.3423
Epoch 88/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.8550 - loss: 0.3585 - val_accuracy: 0.8506 - val_loss: 0.3420
Epoch 89/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8583 - loss: 0.3555 - val_accuracy: 0.8506 - val_loss: 0.3428
Epoch 90/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8502 - loss: 0.3429 - val_accuracy: 0.8506 - val_loss: 0.3424
Epoch 91/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8779 - loss: 0.3475 - val_accuracy: 0.8506 - val_loss: 0.3437
Epoch 92/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8648 - loss: 0.3513 - val_accuracy: 0.8506 - val_loss: 0.3449
Epoch 93/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8713 - loss: 0.3567 - val_accuracy: 0.8506 - val_loss: 0.3448
Epoch 94/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8697 - loss: 0.3489 - val_accuracy: 0.8506 - val_loss: 0.3442
Epoch 95/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8648 - loss: 0.3510 - val_accuracy: 0.8506 - val_loss: 0.3441
Epoch 96/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8811 - loss: 0.3467 - val_accuracy: 0.8506 - val_loss: 0.3435
Epoch 97/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8730 - loss: 0.3410 - val_accuracy: 0.8506 - val_loss: 0.3443
Epoch 98/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8648 - loss: 0.3446 - val_accuracy: 0.8571 - val_loss: 0.3440
Epoch 99/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8567 - loss: 0.3455 - val_accuracy: 0.8636 - val_loss: 0.3439
Epoch 100/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.8599 - loss: 0.3514 - val_accuracy: 0.8636 - val_loss: 0.3447
Epoch 101/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.8730 - loss: 0.3217 - val_accuracy: 0.8636 - val_loss: 0.3461
Epoch 102/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.8616 - loss: 0.3551 - val_accuracy: 0.8571 - val_loss: 0.3470
Epoch 103/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.8730 - loss: 0.3396 - val_accuracy: 0.8636 - val_loss: 0.3460
Epoch 104/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.8795 - loss: 0.3403 - val_accuracy: 0.8636 - val_loss: 0.3441
Epoch 105/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.8632 - loss: 0.3375 - val_accuracy: 0.8636 - val_loss: 0.3458
Epoch 106/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.8713 - loss: 0.3243 - val_accuracy: 0.8636 - val_loss: 0.3458
Epoch 107/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.8876 - loss: 0.3306 - val_accuracy: 0.8636 - val_loss: 0.3433
Epoch 108/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.8648 - loss: 0.3749 - val_accuracy: 0.8636 - val_loss: 0.3425
Epoch 109/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.8730 - loss: 0.3345 - val_accuracy: 0.8636 - val_loss: 0.3424
Epoch 110/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.8681 - loss: 0.3545 - val_accuracy: 0.8636 - val_loss: 0.3433
Epoch 111/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8632 - loss: 0.3478 - val_accuracy: 0.8636 - val_loss: 0.3430
Epoch 112/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8664 - loss: 0.3346 - val_accuracy: 0.8701 - val_loss: 0.3436
Epoch 113/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8713 - loss: 0.3435 - val_accuracy: 0.8636 - val_loss: 0.3443
Epoch 114/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8746 - loss: 0.3418 - val_accuracy: 0.8701 - val_loss: 0.3440
Epoch 115/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.8925 - loss: 0.3312 - val_accuracy: 0.8701 - val_loss: 0.3428
Epoch 116/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.8827 - loss: 0.3313 - val_accuracy: 0.8701 - val_loss: 0.3417
Epoch 117/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8795 - loss: 0.3309 - val_accuracy: 0.8701 - val_loss: 0.3433
Epoch 118/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.8762 - loss: 0.3337 - val_accuracy: 0.8701 - val_loss: 0.3448
Epoch 119/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8827 - loss: 0.3350 - val_accuracy: 0.8701 - val_loss: 0.3466
Epoch 120/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8713 - loss: 0.3453 - val_accuracy: 0.8701 - val_loss: 0.3466
Epoch 121/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.8762 - loss: 0.3555 - val_accuracy: 0.8701 - val_loss: 0.3455
Epoch 122/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8762 - loss: 0.3418 - val_accuracy: 0.8701 - val_loss: 0.3453
Epoch 123/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8844 - loss: 0.3352 - val_accuracy: 0.8701 - val_loss: 0.3458
Epoch 124/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8713 - loss: 0.3542 - val_accuracy: 0.8701 - val_loss: 0.3466
Epoch 125/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8746 - loss: 0.3357 - val_accuracy: 0.8701 - val_loss: 0.3486
Epoch 126/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8632 - loss: 0.3518 - val_accuracy: 0.8701 - val_loss: 0.3474
Epoch 127/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.8746 - loss: 0.3308 - val_accuracy: 0.8701 - val_loss: 0.3474
Epoch 128/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8811 - loss: 0.3348 - val_accuracy: 0.8701 - val_loss: 0.3461
Epoch 129/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8844 - loss: 0.3148 - val_accuracy: 0.8701 - val_loss: 0.3455
Epoch 130/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8730 - loss: 0.3264 - val_accuracy: 0.8701 - val_loss: 0.3469
Epoch 131/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8697 - loss: 0.3477 - val_accuracy: 0.8701 - val_loss: 0.3470
Epoch 132/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8860 - loss: 0.3330 - val_accuracy: 0.8701 - val_loss: 0.3474
Epoch 133/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8779 - loss: 0.3245 - val_accuracy: 0.8701 - val_loss: 0.3454
Epoch 134/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8795 - loss: 0.3427 - val_accuracy: 0.8701 - val_loss: 0.3473
Epoch 135/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8925 - loss: 0.3428 - val_accuracy: 0.8701 - val_loss: 0.3462
Epoch 136/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8844 - loss: 0.3194 - val_accuracy: 0.8701 - val_loss: 0.3461
Epoch 137/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8713 - loss: 0.3434 - val_accuracy: 0.8701 - val_loss: 0.3462
Epoch 138/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8827 - loss: 0.3330 - val_accuracy: 0.8701 - val_loss: 0.3447
Epoch 139/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8681 - loss: 0.3517 - val_accuracy: 0.8701 - val_loss: 0.3449
Epoch 140/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8762 - loss: 0.3442 - val_accuracy: 0.8701 - val_loss: 0.3463
Epoch 141/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8860 - loss: 0.3395 - val_accuracy: 0.8701 - val_loss: 0.3480
Epoch 142/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8860 - loss: 0.3155 - val_accuracy: 0.8701 - val_loss: 0.3458
Epoch 143/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8681 - loss: 0.3425 - val_accuracy: 0.8701 - val_loss: 0.3464
Epoch 144/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8893 - loss: 0.3230 - val_accuracy: 0.8701 - val_loss: 0.3448
Epoch 145/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8827 - loss: 0.3387 - val_accuracy: 0.8701 - val_loss: 0.3445
Epoch 146/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8811 - loss: 0.3326 - val_accuracy: 0.8701 - val_loss: 0.3447
Epoch 147/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8779 - loss: 0.3356 - val_accuracy: 0.8701 - val_loss: 0.3448
Epoch 148/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8713 - loss: 0.3555 - val_accuracy: 0.8701 - val_loss: 0.3452
Epoch 149/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8925 - loss: 0.3355 - val_accuracy: 0.8701 - val_loss: 0.3471
Epoch 150/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8958 - loss: 0.3186 - val_accuracy: 0.8701 - val_loss: 0.3482
Epoch 151/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8795 - loss: 0.3279 - val_accuracy: 0.8701 - val_loss: 0.3487
Epoch 152/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8909 - loss: 0.3232 - val_accuracy: 0.8701 - val_loss: 0.3491
Epoch 153/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8779 - loss: 0.3296 - val_accuracy: 0.8701 - val_loss: 0.3472
Epoch 154/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8974 - loss: 0.3260 - val_accuracy: 0.8701 - val_loss: 0.3486
Epoch 155/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8811 - loss: 0.3197 - val_accuracy: 0.8636 - val_loss: 0.3492
Epoch 156/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8844 - loss: 0.3299 - val_accuracy: 0.8701 - val_loss: 0.3497
Epoch 157/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8697 - loss: 0.3380 - val_accuracy: 0.8701 - val_loss: 0.3495
Epoch 158/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8811 - loss: 0.3365 - val_accuracy: 0.8701 - val_loss: 0.3483
Epoch 159/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8811 - loss: 0.3400 - val_accuracy: 0.8701 - val_loss: 0.3478
Epoch 160/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8893 - loss: 0.3030 - val_accuracy: 0.8701 - val_loss: 0.3499
Epoch 161/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8762 - loss: 0.3484 - val_accuracy: 0.8701 - val_loss: 0.3513
Epoch 162/200